### ISSUE TITLE
Is it possible to create a non-cached UI?

### ISSUE THREAD

**Issue by daattali** [rstudio/py-shiny#269]
In R-shiny, wrapping the UI in a `function(req)` results in a UI that gets generated on runtime of every session. This means that we can have some dynamic content in the UI.

I couldn't find anything in the documentation nor with experimentation that shows this feature in py-shiny.

**Comment by chenson2018** [comment]
I think that this would be a great feature to explicitly include and document. In my opinion it is useful and common enough to deserve a decorator or argument for this behavior (and an R equivalent).

**Comment by jcheng5** [comment]
Not currently but absolutely is coming, as it's necessary for bookmarkable state if nothing else. I think it'll be as simple as `def app_ui(request): ...` instead of `app_ui = ...`

**Comment by jcheng5** [comment]
@chenson2018 It works in R, it's just `ui <- function(req) { ... }`. See the examples [here](https://shiny.rstudio.com/articles/bookmarking-state.html).
