### ISSUE TITLE
Reason for inconsistency in naming scheme for decorators?

### ISSUE THREAD

**Issue by daattali** [rstudio/py-shiny#272]
I assume there must be a good reason for this, but just in the small chance that maybe this is just an oversight: why are some decorators in all small case (`reactive.event`, `reactive.render`) while others have upper case in second word (`reactive.Calc`, `reactive.Effect`)?

**Comment by jcheng5** [comment]
Good question. The latter ones are constructors—they're turning decorated functions into objects. Whereas `reactive.event` takes and returns a function.

**Comment by daattali** [comment]
Got it. Is there a difference from the user's perspective, does the user need to know `reactive.event` vs `reactive.Effect` work differently? Maybe for python users this makes intuitive sense, but for me it feels weird to have to remember to capitalize some but not others.
