### ISSUE TITLE
Suggestion: inputs should return a consistent type

### ISSUE THREAD

**Issue by daattali** [rstudio/py-shiny#273]
For example, a numeric input currently returns either an integer or a float, depending on the number the user inputs. Example:

```
from shiny import App, render, ui

app_ui = ui.page_fluid(
    ui.input_numeric("x", None, value=10.0),
    ui.input_numeric("y", None, value=10.1),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):
    @output
    @render.text
    def txt():
        return f"x: {type(input.x())}, y: {type(input.y())}"


app = App(app_ui, server)

```

**Comment by machow** [comment]
No preference either way--but for some useful context: mypy considers an int to be compatible with float, since they're almost always interchangeable

https://mypy.readthedocs.io/en/stable/duck_type_compatibility.html

**Comment by cpsievert** [comment]
Closing since I don't think we'd do anything for this particular example, but feel free to open another issue if you come across another case
