### ISSUE TITLE
WOW - also - classes? conda?

### ISSUE THREAD

**Issue by vnijs** [rstudio/py-shiny#277]
Never thought I'd see a shiny-for-python. I was a pretty early adopter of shiny for R and still love it. However, I'm really looking forward to learning about shiny-for-python. Very exciting. I assume this is what @jcheng5 presented at Rstudioconf? Can't wait to see the video.

Question 1: Will there be an option to create classes of inputs with inheritance? In shiny-for-R I often have large UIs that are similar across different tools but with subtle differences. Classes seem like a great way to reuse large chunks of code for UIs.

Question 2: Any plans to make shiny-for-python available on conda-forge?

**Comment by sugatoray** [comment]
About conda-forge: please see the following issue.

- #280

**Comment by cpsievert** [comment]
> Question 1: Will there be an option to create classes of inputs with inheritance?

In short, yes, just provide a `tagify()` method on your class and `{shiny}` (via `{htmltools}`) will use that method to serialize an instance of that class to HTML. A basic example:

```py
from htmltools import div, HTMLDocument

class MyUI:
    def __init__(self, *args, **kwargs):
        self._args = args
        self._kwargs = kwargs

    def tagify(self):
        return div(*self._args, **self._kwargs)

doc = HTMLDocument(MyUI("Hello World", style="color: red"))

doc.save_html("hello.html")
```
