### ISSUE TITLE
Add a `conda` install option for `shiny`

### ISSUE THREAD

**Issue by sugatoray** [rstudio/py-shiny#280]
A conda installation option could be very helpful. I have already started working on this, to add `shiny` to conda-forge.

Conda-forge PR: 

- https://github.com/conda-forge/staged-recipes/pull/19842

Once the conda-forge PR is merged, you will be able to install the library with conda as follows:

```sh
conda install -c conda-forge shiny
```

:bulb: I will push a PR to update the docs once the package is available on conda-forge.

**Comment by ivaquero** [comment]
I managed to install htmltools, but failed to install shiny. Is Python 3.10 not supported ?

OS: macOS Monterrey M1
Python: 3.10.5

**Comment by sugatoray** [comment]
Shiny hasn't been added to conda-forge yet. I will take care of it.

**Comment by wch** [comment]
Just fyi:  I released an update to shiny yesterday, v0.2.3, which fixes a significant bug with static deployment. (I saw that the conda-forge PR had 0.2.2.)

**Comment by ivaquero** [comment]
Now I see shiny 0.2.3 on conda-forge. Thanks for all your effort!

**Comment by sugatoray** [comment]
Great. Let me update the docs with the conda install option.

**Comment by jcheng5** [comment]
@sugatoray Thank you for this! I added conda install instructions to https://shiny.rstudio.com/py/docs/install.html. Are we all set on the conda front then? If so, I will go ahead and close this issue.

**Comment by sugatoray** [comment]
@jcheng5 Thank you. Yes, it's added to conda-forge and am maintaining it as well, as newer versions come up on PyPI. 

Would you be able to add me here as a contributor to `py-shiny`, since the work necessary for adding to conda-forge has to happen in conda-forge repositories?

**Comment by jcheng5** [comment]
Thank you so much, @sugatoray!

> Would you be able to add me here as a contributor to py-shiny, since the work necessary for adding to conda-forge has to happen in conda-forge repositories?

Sorry, can you clarify what you mean by this? It's possible to add you as a GitHub collaborator but with the GitHub plan we're on, we pay for each outside collaborator we add, so I'd like to understand the need.
