### ISSUE TITLE
Add render.plotly and output_plotly for plotly graphs

### ISSUE THREAD

**Issue by tst4col** [rstudio/py-shiny#282]
It would be great if one could include `plotly` graphs generated by `plotly` or `plotly.express`. 
One would probably need the analogs to `plotlyOutput` and `renderPlotly` in Shiny-For-R. The standard `output_plot` and `@render.plot` generate an error message suggesting "requesting support for this type of plot object". See [Example](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMArhzxM6lACZw6EgILoAOhD4ChTVFAjSoLVesHDUAG2JlT2DHAAeqKSxZN9W26tVpUAfTFMAvKIcWFAA5nDeNKZi0gAUqkyJQRjEImSoad5mFvEo3iyEUGQUdFnmZMpgAJR4qlUeunA0rHIAbnKxXBlkEqnpaRIscE4cpFWICUkAAn3dk4lTUo10WOXzTLLNUPmFxXJlOePrSZJwZCJ0EG4YBUUlsbb+wAAMEgCMEgBMEgDMEgAsAF0JNgnq8mB8mP8JABOd4ANkB9QgnnQASYSlQsS8vnELTo7ToyLAAF9AUA).

**Comment by cpsievert** [comment]
`output_plot()`/`render.plot` are only designed to support static images. For rendering of interactive widgets, see https://github.com/rstudio/py-shinywidgets
