### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by j-dominguez9** [rstudio/py-shiny#293]
App runs perfectly fine on local machine (VS code, Python 3.10), but upon deployment (Shinylive and Rsconnect), crashes. Recieves following error on shinylive.io:

AttributeError: module 'ssl' has no attribute '_create_default_https_context'

For reference: 
Gist: https://gist.github.com/j-dominguez9/fe652ec2e8c8acb0654ea6e229d47365

Shinylive: https://shinylive.io/py/editor/#gist=fe652ec2e8c8acb0654ea6e229d47365

Screenshots of running fine on VSCode and error on Shinylive, respectively:

![image](https://user-images.githubusercontent.com/83036592/182219895-20e08446-6126-40cb-b5f4-28f1b46c899b.png)

![image](https://user-images.githubusercontent.com/83036592/182219964-6a0c049f-72b4-4106-b7e7-e697059a36de.png)

**Comment by cpsievert** [comment]
Do you the same (or different?) error when deploying to connect?

**Comment by j-dominguez9** [comment]
With connect, it is able to come out in the apps dashboard, but it stays "undeployed" as status. If you click the open window, a blank new browser screen opens, but no content.

**Comment by wch** [comment]
Regarding the Connect deployment, do you have the correct version of Connect?
  https://shiny.rstudio.com/py/docs/deploy.html#deploy-to-rstudio-connect-commercial

With the app on shinylive, it probably has to do with downloading from https. You have the following code:

```py
pd.read_csv('https://raw.githubusercontent.com/j-dominguez9/ML1_Proj1/main/Data/census_clean.csv')
```

And it looks like pandas is using `urllib.request`, which doesn't currently work in Pyodide. 
  https://pyodide.org/en/stable/project/roadmap.html#http-client-limit

In Shinylive, you can use the `pyodide.http.pyfetch`:
  https://pyodide.org/en/stable/usage/faq.html#how-can-i-load-external-files-in-pyodide

Also see download.py in this example for a simple wrapper that will allow you to download files in both regular shiny and shinylive.
  https://shinylive.io/py/examples/#fetch-data-from-a-web-api
