### ISSUE TITLE
Will Shiny Python Support Splitting UI and Server

### ISSUE THREAD

**Issue by corey-dawson** [rstudio/py-shiny#295]
Applications code can get quite long. In R, there is a very nice strucutre of having a global.R, ui.R, and server.R file. Will this structure be supported with python?

**Comment by wch** [comment]
We don't have plans to do this for Python, but you achieve something similar using Python's `import` mechanism. For example, suppose you have files name app.py, ui.py, and server.py. You could put this in your app.py:

```py
## app.py
from shiny import App

from ui import app_ui
from server import server

app = App(app_ui, server)
```

**Comment by jcheng5** [comment]
And `global.R` doesn't make too much sense in Python, which is so heavily based on modules. Probably just make a common module that is imported by both ui.py and server.py.

**Comment by icejean** [comment]
I notice a key difference between the app structure of R Shiny and Shiny for Python of whether having a global.R file.

The global.R, ui.R and server.R style is a typical MVC software development model,  in R Shiny we get a global.R file as the Model part, so when we're developing an app with a well turned stable Model, for example in machine learning applications, we'll load the Models in global.R, and develop the View part ui.R and Control part server.R iteratively,  so when ui.R or server.R is modified, the app will be reloaded automaticaly with just  ui.R or server.R is reloaded, not global.R, this is much more faster  and more convenient than reloading the whole app, as reloading global.R may cost a long long time, over 1 minute for example.

But in the case of app.py in Shiny for Python, any modification of the source will cause the whole app being reloaded automaticaly,  this is really inconvenient for iterative development of a heavy Model Shiny APP,  so my opinion is that,  splitting global.py, ui.py and server.py is a better solution for it.
