### ISSUE TITLE
How do you properly use app.stop()

### ISSUE THREAD

**Issue by ChandlerTayek** [rstudio/py-shiny#297]
I know this might not be the right place to ask but I can't find a single example of how to properly stop the server calling app.stop(). Could someone provide me an example of how to stop the server? I'm trying to configure my shiny app to stop the server after a session closes.

**Comment by jcheng5** [comment]
Can you try `sys.exit()`?

**Comment by ChandlerTayek** [comment]
I modified the "Getting Started" example and tried calling `sys.exit()` when the session closes:

```python
from shiny import App, render, ui
import sys

app_ui = ui.page_fluid(
    ui.h2("Hello Shiny!"),
    ui.input_slider("n", "N", 0, 100, 20),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):

    def close_server():
        print("Attempting to close server.")
        sys.exit()

    session.on_ended(close_server)

    @output
    @render.text
    def txt():
        return f"n*2 is {input.n() * 2}"


app = App(app_ui, server)
app.run()
```

But I get a large traceback starting with "Exception in ASGI application"

After which the server is still running and I can still connect to it hitting the refresh button on the page open in the browser.

**Comment by jcheng5** [comment]
How about `os.kill(os.getpid(), signal.SIGINT)` (on Mac and Linux at least)?

**Comment by ChandlerTayek** [comment]
Thank you so much @jcheng5. Been wracking my brain about this for a couple hours now and didn't think to try that. Worked for me on windows. Here is the working example for those that are interested: 
```python
import signal
from shiny import App, render, ui
import os

app_ui = ui.page_fluid(
    ui.h2("Hello Shiny!"),
    ui.input_slider("n", "N", 0, 100, 20),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):

    def close_server():
        print("Attempting to close server.")
        os.kill(os.getpid(), signal.SIGINT)
        print("Finished")

    session.on_ended(close_server)

    @output
    @render.text
    def txt():
        return f"n*2 is {input.n() * 2}"


app = App(app_ui, server)
app.run()
```

**Comment by ChandlerTayek** [comment]
Thank you so much @jcheng5. Been wracking my brain about this for a couple of hours now and didn't think to try that. Worked for me on windows. Here is the working example for those that are interested:

```python
import signal
from shiny import App, render, ui
import os

app_ui = ui.page_fluid(
    ui.h2("Hello Shiny!"),
    ui.input_slider("n", "N", 0, 100, 20),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):

    def close_server():
        print("Attempting to close server.")
        os.kill(os.getpid(), signal.SIGINT)
        print("Finished")

    session.on_ended(close_server)

    @output
    @render.text
    def txt():
        return f"n*2 is {input.n() * 2}"


app = App(app_ui, server)
app.run()
```
