### ISSUE TITLE
USER REQUIREMENT: conda installation packages 

### ISSUE THREAD

**Issue by richlysakowski** [rstudio/py-shiny#301]
PyShiny is for end users doing analytics.  conda is the primary environment manager and package manager for data analytics and data science, because we need mixed language support (Python, R, JavaScript, HTML, CSS, SQL, and other languages).  It is the preferred format for building robust, reproducible, and portable data science environments.  Pip is a problematic package manager because it does not do environment integrity checking. 

Please provide conda-format packages for all PyShiny tools.  This is an essential requirement.  Take the extra step to facilitate more robust application engineering.

**Comment by jcheng5** [comment]
`conda install -c conda-forge shiny` should work, please give that a try! (See #280)

**Comment by wch** [comment]
@richlysakowski Feedback is welcome, but in the future please drop the condescending attitude. It isn't hard to do -- everyone else who has filed issues on this repository has managed to communicate in a civil manner. The condescension is especially misplaced considering that the two issues you've filed so far have been based in factually incorrect premises.
