### ISSUE TITLE
Use PyShiny, not py-shiny or for installation packages.  Hyphens in object names is not Pythonic

### ISSUE THREAD

**Issue by richlysakowski** [rstudio/py-shiny#302]
Please use the name PyShiny, not py-shiny or anything else for the names of installation packages.  This is a bad naming practice for Python packages.  Putting hyphens in the middle of a string or object name is not Pythonic, because "-" can be interpreted as a "minus sign".  Please use good Python engineering practices.  See PEP8 for more details:  https://peps.python.org/pep-0008/

**Comment by jcheng5** [comment]
Thanks for the feedback. The package name is just `shiny`. Only the GitHub repo is py-shiny.
