### ISSUE TITLE
Is there an easy way to pipe all console ouput (including traceback errors) to a log file?

### ISSUE THREAD

**Issue by ChandlerTayek** [rstudio/py-shiny#305]
I'm trying to set up a production application using py-shiny and the last step before I'm able to release it is being able to log both standard output and errors to a single or separate files. I have looked at lots of resources and there are ways to sort of configure the logging of Uvicorn but I didn't have much success getting both standard output and errors to log files at runtime. 

If anyone has experience with setting this up could you please provide the most basic shiny app that would output log files for standard output and errors (including the traceback). 

This is much appreciated and sorry if this is asking too much or in the wrong place. I really appreciate the dev team on py-shiny and I have very much enjoyed the package thus far. Just stuck on this last hurdle before my release.

**Comment by wch** [comment]
To redirect both stdout and stderr to a file, you should be able to do this:

```bash
shiny run myapp/app.py >>log.txt 2>&1
```

**Comment by ChandlerTayek** [comment]
Just tried this and had no luck getting the traceback to show up in the log file:

Here is the example I was trying:
```python
import signal, os
from shiny import App, render, ui

app_ui = ui.page_fluid(
    ui.h2("Hello Shiny!"),
    ui.input_slider("n", "N", 0, 100, 20),
    ui.output_text_verbatim("txt"),
)
def server(input, output, session):
    print("New connection open!")    
    def close_server():
        print("Session ended so stopping server.")
        os.kill(os.getpid(), signal.SIGINT)
        print("Finished")

    session.on_ended(close_server)

    @output
    @render.text
    def txt():
        if input.n() == 70:
            p = 8/0
        return f"n*2 is {input.n() * 2}"

app = App(app_ui, server)

```

Thanks for the quick feedback but it didn't quite work for me.  When moving the slider to the 70th tick which triggers a divide by zero exception, that error doesn't get carried over to the log file. Maybe I'm doing something wrong here and not realizing it.

**Comment by jcheng5** [comment]
> production application using py-shiny

![image](https://user-images.githubusercontent.com/129551/183779257-68e7456d-f96e-4b34-adfa-bac8163d8d20.png)

Can you say more about how you're attempting to deploy/host this?

**Comment by ChandlerTayek** [comment]
LOL!

I sure can @jcheng5. I have a bit of an odd approach but I'm going to be zipping up the application with pyinstaller and using py-shiny as sort of a front end GUI app to any of my python tools that I will be distributing to my co-workers. Whilst the application is running I want to be able to collect logs or basically information about what the heck is going on so that when the tool breaks (which it will break), I can tell me co-workers to send me the .log (or .txt) file that the application was writing to. 

A bit further down the road I'm going to be pushing these logs to AWS Cloudtrail so that I can have more centralized storage of the logs.

**Comment by ChandlerTayek** [comment]
So I did a bit more digging and was able to configure some logging (note: I'm very new to modifying the logging). I'm still unable to get any logic error traceback to show up in the log file though no matter what level I set the log level to. Any suggestions?

**Comment by ChandlerTayek** [comment]
I wrote an example and posted the question here as well: https://stackoverflow.com/questions/73339022/how-does-one-set-up-traceback-logging-in-py-shiny-which-runs-on-uvinicorn-for-py

**Comment by jcheng5** [comment]
Oh, it was the Pyinstaller piece I was missing. You can add a line like this to the top of your app (the earlier the better):

```python
import sys
sys.stdout = sys.stderr
```

We really should be printing out all of these messages out at stderr, not stdout. I'll file a separate issue for that.

**Comment by ChandlerTayek** [comment]
Correct me if I'm doing something wrong here @jcheng5 but I would assume this snippet would produce a traceback inside the log file

```python
from shiny import App, ui, reactive
import logging
import sys


sys.stdout = sys.stderr
logging.basicConfig(filename='myapp.log', level=logging.INFO)


def ui_card(title, *args):
    return (
        ui.div(
            {"class": "card mb-4"},
            ui.div(title, class_="card-header"),
            ui.div({"class": "card-body"}, *args),
        ),
    )

app_ui = ui.page_fluid(
    ui_card(
        "This button will attempt a divide by zero",
        ui.input_action_button("btn", "Push to Crash"),
    ),
)

def server(input, output, session):

    @reactive.Effect
    @reactive.event(input.btn)
    def _():
        12/0

def create_app():
    return App(app_ui, server)

app = create_app()

app.run()
```

I'm seeing this in the console:
```
←[32mINFO←[0m:     Started server process [←[36m20108←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:8000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     127.0.0.1:62979 - "←[1mGET / HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     127.0.0.1:62979 - "←[1mGET /require.min.js HTTP/1.1←[0m" ←[33m304 Not Modified←[0m
←[32mINFO←[0m:     127.0.0.1:62979 - "←[1mGET /jquery-3.6.0.min.js HTTP/1.1←[0m" ←[33m304 Not Modified←[0m
←[32mINFO←[0m:     127.0.0.1:62979 - "←[1mGET /shiny.js HTTP/1.1←[0m" ←[33m304 Not Modified←[0m
←[32mINFO←[0m:     127.0.0.1:62979 - "←[1mGET /bootstrap.bundle.min.js HTTP/1.1←[0m" ←[33m304 Not Modified←[0m
←[32mINFO←[0m:     ('127.0.0.1', 62988) - "WebSocket /websocket/" [accepted]
←[32mINFO←[0m:     connection open
Traceback (most recent call last):
  File "C:\Users\chand\anaconda3\envs\t\lib\site-packages\shiny\reactive\_reactives.py", line 533, in _run
    await self._fn()
  File "C:\Users\chand\anaconda3\envs\t\lib\site-packages\shiny\_utils.py", line 132, in fn_async
    return fn()
  File "C:\Users\chand\anaconda3\envs\t\lib\site-packages\shiny\reactive\_reactives.py", line 815, in new_user_fn
    return user_fn()
  File "stack_overflow_app.py", line 31, in _
    12/0
ZeroDivisionError: division by zero
C:\Users\chand\anaconda3\envs\t\lib\site-packages\shiny\reactive\_reactives.py:540: ReactiveWarning: Error in Effect: division by zero
  warnings.warn("Error in Effect: " + str(e), ReactiveWarning)
Unhandled error: division by zero
←[32mINFO←[0m:     connection closed
←[32mINFO←[0m:     Shutting down
←[32mINFO←[0m:     Waiting for application shutdown.
←[32mINFO←[0m:     Application shutdown complete.
←[32mINFO←[0m:     Finished server process [←[36m20108←[0m]
```


I'm expecting to see the traceback in the log file but I'm only seeing this:
```
INFO:uvicorn.error:Started server process [20108]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:('127.0.0.1', 62988) - "WebSocket /websocket/" [accepted]
INFO:uvicorn.error:connection open
INFO:uvicorn.error:connection closed
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [20108]
```

Do you mind trying to reproduce this if possible and maybe help me where I'm going wrong? This is my last hurdle till I can deploy it :(. Much appreciative of the responses I have been getting :)

**Comment by jcheng5** [comment]
Can you tell me how to reproduce the Pyinstaller part?

**Comment by ChandlerTayek** [comment]
I can but I'm not able to get it to work by just using app.run(), which to me seems like it should be easier. 

I was able to get pyinstaller to work with this build command:

`pyinstaller app.py -w -F --add-data 'C:\Users\chand\anaconda3\envs\t\Lib\site-packages\shiny;./shiny'`

**Comment by ChandlerTayek** [comment]
Update: I'm able to get tracebacks to hit the log file if I explicitly call `logging.exception()` but I'm hoping there is a better way to catch any un-caught exceptions that might happen.

**Comment by jcheng5** [comment]
OK, I missed the fact that you were calling `logging.basicConfig`. I'd stop doing that for now--we need to fix up our logging to use `logging` everywhere, but for now you should just do this instead, as early as possible:

```python
import sys
logfile = open('myapp.log', 'a', 1)
sys.stdout = logfile
sys.stderr = logfile
```

I'd do this before importing any other packages, so import errors will be logged.

**Comment by ChandlerTayek** [comment]
@jcheng5 Your solution worked for me, thank you so much!

**Comment by ChandlerTayek** [comment]
@jcheng5 Your solution worked for me, thank you so much!
