### ISSUE TITLE
head tag is not moving other tags to head

### ISSUE THREAD

**Issue by Polkas** [rstudio/py-shiny#309]
I expect that head tag will move any internal one to the head space the same as in R shiny.
I think it is not intended to lose this functionality.

minimal example, style will be not moved to head:

```
from shiny import App, ui
from htmltools.tags import head, style, p

# Part 1: ui ----
app_ui = ui.page_fluid(
    # it is still in the body
    head(style("/* head style*/")),
    p("Hello World")
)

# Part 2: server ----
def server(input, output, session):
    ...

# Combine into a shiny app.
# Note that the variable must be "app".
app = App(app_ui, server)
```

I find it out in this app, leave only for reference.
gist:https://gist.github.com/Polkas/2b656d4a4497054a1b931cd3ae12ba1e#file-app-py-L72
app:https://shinylive.io/py/app/#gist=2b656d4a4497054a1b931cd3ae12ba1e

**Comment by wch** [comment]
You can use `ui.head_content()` instead of `ui.head()`.

I believe this change was intentional but I'll have to take a look at the history to see what we were thinking at the time.

**Comment by wch** [comment]
I believe that the reason for using `head_content()` instead of automatically hoisting content in `tags.head()` was because we didn't want to special-case the handling of that one tag.
