### ISSUE TITLE
Support `matplotlib.pyplot` interface (as opposed to matplotlib's object-oriented interface)

### ISSUE THREAD

**Issue by Nelson-Gon** [rstudio/py-shiny#312]
Hello py-shiny team,

Awesome work porting `shiny` to `python`. I would like to know if it is possible to directly call `@render.plot` on a plot object directly. For instance  for https://github.com/rstudio/py-shiny/issues/211, instead of 

```
  @output()
    @render.plot(alt="A histogram")
    def plot():
        np.random.seed(19680801)
        x = 100 + 15 * np.random.randn(437)
        fig, ax = plt.subplots()
        plt.tight_layout()
        ax.hist(x, input.n(), density=True)
        return fig
```

I would like to be able to directly do the following 

```
  @output()
    @render.plot(alt="A histogram")
    def plot():
        np.random.seed(19680801)
        x = 100 + 15 * np.random.randn(437)
        return plt.hist(x, input.n(), density=True)

```

Currently, this will fail with

>@render.plot doesn't know to render objects of type '<class 'tuple'>'. Consider either requesting support for this type of plot object, and/or explictly saving the object to a (png) file and using @render.image

Thank you and sorry if this has already been asked elsewhere. I could not readily find it.

NelsonGon

**Comment by wch** [comment]
Unfortunately, I don't think that `plt.hist()` returns enough information to make a PNG output file. For example:

```
>>> x = np.linspace(-5, 5, 1000)
>>> p = plt.hist(x, 100, density=True)
>>> p
(array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]), array([-5. , -4.9, -4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. ,
       -3.9, -3.8, -3.7, -3.6, -3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9,
       -2.8, -2.7, -2.6, -2.5, -2.4, -2.3, -2.2, -2.1, -2. , -1.9, -1.8,
       -1.7, -1.6, -1.5, -1.4, -1.3, -1.2, -1.1, -1. , -0.9, -0.8, -0.7,
       -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,
        0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,
        2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,
        3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,
        4.9,  5. ]), <BarContainer object of 100 artists>)
>>> p[2]
<BarContainer object of 100 artists>
```

So `p[2]` is a `BarContainer` object, but I don't think that a figure can be constructed from it.

If there is a way of getting an object which can be used to generate a PNG that is simpler than what we currently do, we would consider adding support for it.

**Comment by jcheng5** [comment]
I think we can do this by implementing a custom matplotlib backend. Then you wouldn't return the result of `plt.hist()`, rather, you wouldn't return anything and we'd capture the plot function side-effects. A bit annoying to implement, but this feels like an important use case; I find it frustrating to always have to hunt down the OO API docs for whatever I'm trying to do, when most blog posts/StackOverflow answers seem to use pyplot when possible.

**Comment by jcheng5** [comment]
Alright it turned out to not be nearly that hard. https://github.com/rstudio/py-shiny/pull/314
