### ISSUE TITLE
How are you embedding shinylive in the doc website?

### ISSUE THREAD

**Issue by jamieRowen** [rstudio/py-shiny#317]
I can use shinylive to create a static site standalone version of the application.

Inspecting the generated index.html I can see

```
runApp(appRoot, "viewer", {startFiles: appFiles});
```

which I can effectively leverage to embed the standard view of a shiny app into some other page. I was wondering how I would run the app in the editor mode instead?

**Comment by jamieRowen** [comment]
nevermind, I did not think to inspect edit/index.html which provides the answer, apologies

**Comment by wch** [comment]
Please bear in mind that the Javascript API is not stable, and we are currently in the process of making some changes to it.

In the next few weeks we'll have more of a story to tell about it.

**Comment by jamieRowen** [comment]
noted, thanks
