### ISSUE TITLE
`panel_conditional` does not work when used inside modules

### ISSUE THREAD

**Issue by gcaligari** [rstudio/py-shiny#333]
Great work with Shiny for Python. 

I am aware that it is still in its Alpha version, however while testing out some of its functionality, I have encountered what seems to be a bug with `  ui.panel_conditional`. 

When used in a simple page, eg. within `app_ui = ui.page_fluid(`, it works as intended without issue. However when attempting to use it within a module, eg. within
 ```
@module.ui
def page_ui() -> ui.TagChildArg:
      return  ui.page_fluid(
```
the conditional panel no longer works and does not produce the desired UI pieces. 

Regards,
Giulia

**Comment by jcheng5** [comment]
Thanks for the report! Should be fixed on main now.
