### ISSUE TITLE
Feature Request:  Expose uvicorn "--workers" as a top-level parameter to shiny::run()

### ISSUE THREAD

**Issue by bschulth** [rstudio/py-shiny#335]
- Consider exposing uvicorn `--workers`
   -  https://www.uvicorn.org/settings/#production

- as a top-level parameter to `run()`
   - https://github.com/rstudio/py-shiny/blob/main/shiny/_main.py#L106

- to more easily set the level of concurrency. By default, I think uvicorn starts single-threaded with a single worker.

**Comment by jcheng5** [comment]
Unfortunately, setting `--workers` to >1 can't work with Shiny; Uvicorn's approach to multi-worker does not allow for sticky load balancing, which Shiny requires. It will _appear_ to work but certain features that require XHR/HTTP calls back to the server will randomly fail (for example, `input_file` or `session.download`).

**Comment by bschulth** [comment]
Ah, bummer, I was hoping Python/uvicorn workers was going to overcome the R-single-threaded-behavior and give massive concurrency out of the box, but I get the sticky-session problem.

Perhaps consider checking if the environment variable 'WEB_CONCURRENCY' is set and either fail miserably or issue a stern warning?

I was setting this environment variable to enable this feature for testing concurrent web request s...which for my simple tests appeared to work (as you indicated it might)

Thanks again, great work!

**Comment by jcheng5** [comment]
Thank you for the suggestion, I didn’t realize that `WEB_CONCURRENCY` was a thing!
