### ISSUE TITLE
Push notifications/ Content push using py-shiny

### ISSUE THREAD

**Issue by skye0402** [rstudio/py-shiny#341]
Not a bug but a question: Is it possible to push content to a shiny webpage from the server? Altering the loaded page in the browser from the server side. I didn't find any information in the help. Such a thing is usually realized with websockets.

**Comment by jcheng5** [comment]
Yes, there are multiple ways to do this with Shiny (which uses WebSockets extensively). Can you say more about what exactly you want to do?

**Comment by skye0402** [comment]
@jcheng5 thanks! Use case would be a web page in a kiosk mode showing a qr code that's pushed from the server when an event happened (that's outside of the web page and only the server knows e.g the room temperature exceeds a certain degree).

**Comment by jcheng5** [comment]
Sounds good—and how do you find out the event happened? Make calls to a remote API at a set interval, or something like that?

**Comment by skye0402** [comment]
@jcheng5 I think this [blog](https://www.shanelynn.ie/asynchronous-updates-to-a-webpage-with-flask-and-socket-io/) describes the principle pretty much (link to the github included).
In that a webserver is running (flask) and serves the page and a parallel websocket server (socketio) that pushes random numbers to the page. Instead of the random push I would just put in my logic (e.g. read the external event). 

Now I wonder how this setup would look with shiny e.g. https://shinylive.io/py/examples/#checkbox-input where instead of the checkbox the server would trigger the change of `input.x`

**Comment by skye0402** [comment]
@jcheng5 I think I found the answer I was looking for in this example:
https://shiny.rstudio.com/py/api/reference/shiny.reactive.poll.html#shiny.reactive.poll
Thanks, will close the "incident".
