### ISSUE TITLE
Current CI/CD pipeline for Python 3.7 fails because of issue with `importlib_metadata` and `flake8`

### ISSUE THREAD

**Issue by fpgmaas** [rstudio/py-shiny#348]
Example pipeline that fails: https://github.com/rstudio/py-shiny/actions/runs/3183453613

See also relevant issues [here](https://github.com/python/importlib_metadata/issues/406) and [here](https://github.com/PyCQA/flake8/issues/1701).

**Comment by fpgmaas** [comment]
Tried to fix it with #349, but the issue persists because `flake8>5.0.0` is still installed by [py-htmltools](https://github.com/rstudio/py-htmltools): 
https://github.com/rstudio/py-shiny/actions/runs/3183453613/jobs/5192917088#step:5:21

 I opened a Pull Request in `py-htmltools` as well; https://github.com/rstudio/py-htmltools/pull/44

**Comment by fpgmaas** [comment]
I figured we don't need to install the full `requirements-dev.txt` from `py-htmltools`, but only the `wheel` package. Therefore I propose the following change: https://github.com/rstudio/py-shiny/pull/349/files#diff-038d392b404f94b2ee8e3f10b6ae76784160379d9e90638f78ee65df63353221L36

However, the issue still persists, because the following command:

```
python3 -m pip install --force-reinstall dist/shiny*.whl --find-links ../py-htmltools/dist/
```

seems to install `importlib-metadata 5.0.0` anyway:

https://github.com/rstudio/py-shiny/pull/349/checks#step:7:1711

**Comment by fpgmaas** [comment]
Weirdly enough, after pinning `importlib_metadata` in `setup.cfg`, the tests for Python `3.7` succeed, but they fail for `3.8`.

**Comment by jcheng5** [comment]
@fpgmaas Yeah, I think the random port number generator just happened to pick a port number that browsers refuse to connect to. I'll fix that.

**Comment by fpgmaas** [comment]
@jcheng5 I will close this issue since the original issue seems to be resolved.
