### ISSUE TITLE
Add `ui_pattern` to App

### ISSUE THREAD

**Issue by cvmartin** [rstudio/py-shiny#352]
I've found useful in R to implement an healthpoint `/health` to my Shiny applications, by making small changes to the UI and server side of the application; plus making use of the `uiPattern` argument of `shiny::shinyApp`.

I saw that `uiPattern` was not implemented yet for Shiny Python, so I took a stab at it. I've got an example running in a local branch that involves, roughly:

Passing `ui_pattern` as argument to `App`, and use it in a method to register a custom conversor as [indicated](https://www.starlette.io/routing/) in the starlette docs:
```
    def register_ui_pattern(self):
        class CustomPatternConvertor(Convertor):
            regex = self.ui_pattern

            def convert(self, value: str) -> str:
                return str(value)

            def to_string(self, value: str) -> str:
                return str(value)

        register_url_convertor("custom_ui_pattern", CustomPatternConvertor())
```
And then, inside `init_starlette_app()`, note the use of `{path:custom_ui_pattern}` to add the custom routing other than `/`:
```
def init_starlette_app(self):

        self.register_ui_pattern()

        routes: list[starlette.routing.BaseRoute] = [
            starlette.routing.WebSocketRoute("/websocket/", self._on_connect_cb),
            starlette.routing.WebSocketRoute(
                "/{path:custom_ui_pattern}/websocket/", self._on_connect_cb
            ),
            starlette.routing.Route("/", self._on_root_request_cb, methods=["GET"]),
            starlette.routing.Route(
                "/{path:custom_ui_pattern}", self._on_root_request_cb, methods=["GET"]
            ),
...
```
As a result, the app below (modified from the `ui-func` example) works: when accessing `/`, it loads the application, when accessing `/health`, well, it pings the healthpoint.

```
from datetime import datetime

from starlette.requests import Request

from shiny import App, reactive, render, ui


def app_ui(request: Request):

    if request.url.path == "/health":
        return ui.page_fluid(ui.HTML("<p>ok</p>"))

    return ui.page_fluid(
        ui.div("This page was rendered at ", datetime.now().isoformat()),
        ui.output_text("now"),
    )


def server(input, output, session):

    with reactive.isolate():
        if session.http_conn.url.path == "/health/websocket/":
            return None

    @output
    @render.text
    def now():
        reactive.invalidate_later(0.1)
        return f"The current time is {datetime.now().isoformat()}"


app = App(app_ui, server, ui_pattern="health")
```

Would you consider adding something like this to `main`?

**Comment by jcheng5** [comment]
I think we can do better than `uiPattern` in Shiny for Python; since we're already using starlette, we may as well just use it to add additional routes:

```python
from datetime import datetime

from starlette.routing import Route
from starlette.requests import Request
from starlette.responses import PlainTextResponse

from shiny import App, reactive, render, ui


def app_ui(request: Request):

    return ui.page_fluid(
        ui.div("This page was rendered at ", datetime.now().isoformat()),
        ui.output_text("now"),
    )


def server(input, output, session):
    @output
    @render.text
    def now():
        reactive.invalidate_later(0.1)
        return f"The current time is {datetime.now().isoformat()}"


app = App(app_ui, server)


async def health(request: Request):
    return PlainTextResponse("OK")


app.starlette_app.routes.insert(0, Route("/health", health, methods=["GET"]))
```

I think there are things we can change in Shiny for Python to make this nicer, such as avoiding the need for `routes.insert` which is not a documented behavior in Starlette AFAICT (although [this comment](https://github.com/encode/starlette/issues/1196#issuecomment-856929772) gives an unofficial nod). Right now we have to do this because one of Shiny's own mounts sends a 404 response on unknown URLs, instead of giving additional routes/mounts a chance.

**Comment by cvmartin** [comment]
Thanks a lot for your prompt and complete reply. 

I got from the documentation that routing happens just when instantiating the `App` object, good to know that one can add additional routes afterwards!

All the best
