### ISSUE TITLE
Anyway to access input id of input text ui which created by iteration?

### ISSUE THREAD

**Issue by Suzanoo** [rstudio/py-shiny#354]
I have create text input ui from iteration that number of iteration comes from user input(5 times in example).But I cannot access their ID by using iteration to capture (input.xxx()).Anyway to solve it??

[app.txt](https://github.com/rstudio/py-shiny/files/9830828/app.txt)

**Comment by cpsievert** [comment]
I think you want `input["input_1"]()` instead of `input.input_1()`?
