### ISSUE TITLE
shiny.ui.output_image (api) example does not run due to missing file

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [rstudio/py-shiny#359]
Check https://shiny.rstudio.com/py/api/reference/shiny.ui.output_image.html#

The app is missing a png file.

<img width="874" alt="Screen Shot 2022-10-20 at 3 24 52 PM" src="https://user-images.githubusercontent.com/5369655/197070565-e64604a4-4f87-4098-a910-39f482798687.png">

**Comment by wch** [comment]
Fixed by #340.
