### ISSUE TITLE
shiny.ui.input_action_ documentation examples are broken

### ISSUE THREAD

**Issue by kitchensjn** [rstudio/py-shiny#380]
New to Shiny for Python and reading through documentation. The example histogram plots for shiny.ui.input_action_button and shiny.ui.input_action_link (https://shiny.rstudio.com/py/api/reference/shiny.ui.input_action_button.html) appear to be broken and do not update when "Go" is pressed. Has this functionality changed?

Changing @reactive.event(lambda: input.go, ignore_none=False) to @reactive.event(input.go) fixes the updating, but then requires an initial button press to generate the plot.

**Comment by jcheng5** [comment]
You're so right. `@reactive.event(input.go, ignore_none=False)` is the correct decoration. Thank you!
