### ISSUE TITLE
Can we use plotly in Python Shiny?

### ISSUE THREAD

**Issue by Northbreeze** [rstudio/py-shiny#388]
I've added a plotly chart but I got the below error:

`
  @output
  @render.plot
  def network_plot():
      import plotly.express as px
      df = px.data.gapminder()

      fig = px.scatter(df.query("year==2007"), x="gdpPercap", y="lifeExp",
	       size="pop", color="continent",
               hover_name="country", log_x=True, size_max=60)

      return fig
 `
 @render.plot doesn't know to render objects of type '<class 'plotly.graph_objs._figure.Figure'>'. Consider either requesting support for this type of plot object, and/or explicitly saving the object to a (png) file and using @render.image.

**Comment by cpsievert** [comment]
Yes, see the other relevant issues https://github.com/rstudio/py-shiny/issues?q=is%3Aissue+plotly+is%3Aclosed

**Comment by professorf** [comment]
Do you think you could make it easier like in R? The solution suggested is basically a kludge because plotly isn't properly supported.

For example, in R you just have to do:
# ... do all your drawing into p ...
ggplotly(p)

Thank you
