### ISSUE TITLE
shiny run WinError 10013

### ISSUE THREAD

**Issue by Renfle91** [rstudio/py-shiny#389]
Hi,

I have an issue when I try to run a shiny app. I get the following message:

(fco) C:\Users\fco\Documents>shiny run --reload my_app\app.py
←[32mINFO←[0m:     Will watch for changes in these directories: ['C:\\Users\\fco\\Documents\\my_app']
←[31mERROR←[0m:    [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

Thank you for your help.

**Comment by jcheng5** [comment]
Thanks for the report!

1. Does it happen every time?
2. Does it make a difference if you don’t include `—reload`?
3. What if you add `—port 0`?

**Comment by Renfle91** [comment]
Hi jcheng5,

It worked when I added --port 0.

Thank you very much for your fast reply and your help.
