### ISSUE TITLE
`input_selectize` and `input_selected` ignore `selected=None` option

### ISSUE THREAD

**Issue by OksanaBash** [rstudio/py-shiny#398]
Hi! Thanks a lot for a great package:) I have noticed that the mentioned functions ignore the `selected` argument once its value is set to `None`. The selected option is the first one in the list of choices. This behavior is observed in any setup I have tried, as well as in the [provided example](https://shiny.rstudio.com/py/api/reference/shiny.ui.input_select.html ):
```
from shiny import *

app_ui = ui.page_fluid(
    ui.input_select(
        "state",
        "Choose a state:",
        {
            "East Coast": {"NY": "NY", "NJ": "NJ", "CT": "CT"},
            "West Coast": {"WA": "WA", "OR": "OR", "CA": "CA"},
            "Midwest": {"MN": "MN", "WI": "WI", "IA": "IA"},
        },
        selected=None
    ),
    ui.output_text("value"),
)

def server(input: Inputs, output: Outputs, session: Session):
    @output
    @render.text
    def value():
        return "You choose: " + str(input.state())


app = App(app_ui, server)

```
This behavior is inconsistent with the documentation as well as with some other input UIs. For example, `input_checkbox_group` reacts to `selected=None`as expected, by not selecting anything initially.

**Comment by GShotwell** [comment]
Hi Oksana,

Thanks for the report and the reproducible example. I think this is maybe confusing documentation. The `selected = None` option only suppresses the initial input when you have multiple select enabled, but we need to clarify this in the documentation. 

You can of course generate a blank default value for the select input by including it as an option. 

```
 ui.input_select(
        "state",
        "Choose a state:",
        {
            " ": {" ": " "},
            "East Coast": {"NY": "NY", "NJ": "NJ", "CT": "CT"},
            "West Coast": {"WA": "WA", "OR": "OR", "CA": "CA"},
            "Midwest": {"MN": "MN", "WI": "WI", "IA": "IA"}
        },
        selected= " "
    )` 
```

**Comment by OksanaBash** [comment]
Hi Gordon, thank you for the clarification. I think I can close the issue now.
