### ISSUE TITLE
Calling function to start a shiny-for-python app from a jupyter notebook?

### ISSUE THREAD

**Issue by vnijs** [rstudio/py-shiny#403]
It is possible launch an R-shiny app from a jupyter-notebook running an R-kernel. It opens up in a new tab. Could something similar be done for a shiny-for-python app? For example, calling a function or instantiating a class that starts a shiny app.

I was hoping that something like the below might work (but then wrapped in a function) but that returns: `RuntimeError: asyncio.run() cannot be called from a running event loop`

```
from shiny import *
from shinywidgets import output_widget, register_widget, reactive_read
import ipyleaflet as L

app_ui = ui.page_fluid(
    ui.input_slider("zoom", "Map zoom level", value=4, min=1, max=10),
    output_widget("map"),
    ui.output_text("map_bounds"),
)

def server(input, output, session):

    # Initialize and display when the session starts (1)
    map = L.Map(center=(52, 360), zoom=4)
    register_widget("map", map)

    # When the slider changes, update the map's zoom attribute (2)
    @reactive.Effect
    def _():
        map.zoom = input.zoom()

    # When zooming directly on the map, update the slider's value (2 and 3)
    @reactive.Effect
    def _():
        ui.update_slider("zoom", value=reactive_read(map, "zoom"))

    # Everytime the map's bounds change, update the output message (3)
    @output
    @render.text
    def map_bounds():
        b = reactive_read(map, "bounds")
        lat = [b[0][0], b[0][1]]
        lon = [b[1][0], b[1][1]]
        return f"The current latitude is {lat} and longitude is {lon}"

run_app(App(app_ui, server))
```

May be related to https://github.com/rstudio/py-shiny/issues/303

**Comment by jcheng5** [comment]
I can’t say this is something I’d recommend/support, but you could try one of the approaches here: https://stackoverflow.com/questions/74070505/how-to-run-fastapi-application-inside-jupyter (Note that the Shiny `app` object is a Uvicorn app.)

**Comment by vnijs** [comment]
Thanks Joe. I'll try it out. Is something like jupyter-dash feasible/likely for shiny-for-python?

https://github.com/plotly/jupyter-dash

**Comment by jcheng5** [comment]
Seems feasible, can you say more about what is interesting to you about this?

**Comment by vnijs** [comment]
Students can do a lot with a tool like Radiant that generates R-code for them. Although python basics are relatively easy to learn, data analysis in python has a steeper learning curve for many students. I'm envisioning mini shiny-for-python apps launched from jupyter (or perhaps Quarto in an interactive session) that could run some analysis, show output, and return python code on completion. For example, load some data using pandas (or another mini-app) and then develop a regression model using shiny-ui elements to select the targets and features. When done, the user closes the app and code would be returned to make the analysis reproducible.

```python
import pandas as pd
import my_module as mm
data = pd.read_csv("data/penguins.csv")
reg_code = mm.regression(data)
print(reg_code)
```

As an example of something (much) larger than what I have in mind, see https://www.trymito.io/ Mito integrates nicely with jupyter and focuses on pandas and visualization.

**Comment by vnijs** [comment]
Another example of an app that nicely ingrates with jupyter and focuses on pandas and visualization: https://github.com/Kanaries/pygwalker

**Comment by vnijs** [comment]
This is pretty cool as well. Renders streamlit ui elements in a jupyter notebook.

https://github.com/ddobrinskiy/streamlit-jupyter

@jcheng5 Can you give an indication if this is (not) likely to land on the development path? I have some students working on projects right now and would (much) prefer to have them work with Shiny-for Python if possible

**Comment by vnijs** [comment]
I tried both (suggestions)[https://stackoverflow.com/a/74071421/1974918] and the 2nd option (`launch_nest`) seems to do something version similar to running a shiny app from Rstudio. Seems to work fine when run from a jupyter notebook as well.

@jcheng5: You mentioned "I can’t say this is something I’d recommend/support". Can you say more about the downside of this approach?

```python
from shiny import App, render, ui, reactive, Inputs, Outputs, Session
import uvicorn
import asyncio
import nest_asyncio
import webbrowser
import polars as pl


class radiant_data:
    def __init__(self, dataset: pl.DataFrame) -> None:
        self.dataset = dataset

    def data_ui(self):
        return ui.page_fluid(ui.output_table("show_data"))

    def data_server(self, input: Inputs, output: Outputs, session: Session):
        @reactive.Calc
        def load_data():
            return self.dataset

        @output(id="show_data")
        @render.table
        def show_data():
            return load_data()


def launch(data):
    # need to ensure the process is stopped
    rd = radiant_data(data)
    config = uvicorn.Config(App(rd.data_ui(), rd.data_server), port=8000)
    server = uvicorn.Server(config)
    loop = asyncio.get_running_loop()
    loop.create_task(server.serve())
    webbrowser.open("http://127.0.0.1:8000")


def launch_nest(data):
    # locks interactive session
    rd = radiant_data(data)
    nest_asyncio.apply()
    webbrowser.open("http://127.0.0.1:8000")
    uvicorn.run(App(rd.data_ui(), rd.data_server), port=8000)


mydata = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

# launch(mydata)
launch_nest(mydata)
```

**Comment by wch** [comment]
For future reference, it is possible to launch a Shiny application without blocking, using hypercorn as the ASGI server in stead of uvicorn. Hypercorn also makes it possible to stop an individual app gracefully, without affecting any other apps that are running in the same process.

This can be useful within a Jupyter notebook. Here's an example:

```py
import asyncio

from shiny import App, Inputs, Outputs, Session, render, ui

app_tasks: list["AppTask"] = []


class AppTask:
    def __init__(self, app: App, port: int) -> None:
        self.shutdown_event = asyncio.Event()
        self.app = app
        self.port = port
        self.task = asyncio.create_task(self.start())
        app_tasks.append(self)

    async def start(self) -> None:
        import hypercorn.asyncio
        import hypercorn.config

        config = hypercorn.config.Config()
        config.bind = [f"localhost:{self.port}"]

        await hypercorn.asyncio.serve(
            App(app_ui, server),
            config,
            shutdown_trigger=self.shutdown_event.wait,
        )

    def stop(self):
        self.shutdown_event.set()


def stop_all_apps():
    for task in app_tasks:
        task.stop()

# ===========

app_ui = ui.page_fluid(
    ui.input_slider("n", "N", 0, 100, 10),
    ui.output_text_verbatim("val"),
)


def server(input: Inputs, output: Outputs, session: Session):
    @output
    @render.text
    def val():
        return "N * 2 is " + str(input.n() * 2)

# ===========

# Launch the app, nonblocking
AppTask(App(app_ui, server), 8000)
```

At this point, the app can be visited in another browser window by visiting port 8000, or by using an iframe in the Jupyter notebook, like this:

```
%%html
<iframe src="http://localhost:8000/" width="600" height="300"></iframe>
```

To stop the app, you can run:

```py
stop_all_apps()
```

Screenshot of the app running in an iframe in the notebook:

<img width="984" alt="image" src="https://github.com/rstudio/py-shiny/assets/86978/fdb32dc3-41f9-4b53-898e-9d68cadb90c8">

**Comment by Salfo** [comment]
@wch I was hopping that your solution will work on Azure databricks, but the AppTask class is failing with the following error:
TypeError: 'type' object is not subscriptable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command-4113901137733978> in <module>
      3 from shiny import App, Inputs, Outputs, Session, render, ui
      4 
----> 5 app_tasks: list["AppTask"] = []
      6 
      7 class AppTask:

TypeError: 'type' object is not subscriptable

Any help? Thank you
I am knew to python and databricks. Forgive me if I am asking a trivial question.
