### ISSUE TITLE
ImportError when launching "Plotly" and "Map" shiny examples. 

### ISSUE THREAD

**Issue by fcusimano** [rstudio/py-shiny#411]
Hello, you might already be aware, but I get this error when opening the "Plotly" and "Map" shiny examples on the website. I also have the error when trying to run the examples locally.

`ImportError: cannot import name '_package_dir' from 'htmltools._util' (/lib/python3.10/site-packages/htmltools/_util.py)`

**Comment by wch** [comment]
Thanks - I see the source of the problem and will put out a fix shortly.
