### ISSUE TITLE
e2e tests don't use currently-installed versions of packages

### ISSUE THREAD

**Issue by wch** [rstudio/py-shiny#417]
In our GHA workflow, we are manually installing htmltools from github, but the e2e tests aren't recognizing that installed copy of htmltools.

Error here:
https://github.com/rstudio/py-shiny/actions/runs/4359881025/jobs/7622174378#step:13:23

Installation of correct version of htmltools here:
https://github.com/rstudio/py-shiny/actions/runs/4359881025/jobs/7622174378#step:5:28

**Comment by schloerke** [comment]
Related #414

**Comment by schloerke** [comment]
@jcheng5 May we remove `tox` as a testing wrapper? If so, we can just use the installed packages with pytest.

I do remember you saying that `tox` can test in multiple platforms, but we have this with GHA testing. So I do not believe the duplication of e2e dependencies and headache of trying to get GitHub dependencies installed within tox.

I've added a `make test-e2e` command in https://github.com/rstudio/py-shiny/pull/418/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52
