### ISSUE TITLE
render image-embedded HTML content, 404 not found

### ISSUE THREAD

**Issue by ZihuiWang1** [rstudio/py-shiny#421]
Hi,

Not sure if it's an issue but I have been struggling for days, would be very grateful if you could help with the solution.

I want to reactively render a HTML file with images embedded in it, and had the error 
`127.0.0.1:63156 - "GET /images/1732051001.png HTTP/1.1" 404 Not Found`

The html file includes a bunch of `<img src="images/***.png" style="width:256px">` and is under the same fold with `images`, however, I don't think I put the `images` in the right place for `app.py` to find them. 

the `app.py`
```
from shiny import *

app_ui = ui.page_fluid(
    ui.output_ui('con'),
)

def server(input, output, session):
    @output
    @render.ui
    def con():
        with open('index.html', 'r') as htmls:
            html_string = htmls.read()
        return ui.HTML(html_string)

app = App(app_ui, server)
```

**Comment by wch** [comment]
If you want to serve already-existing .png files, you can do something like [this example](https://shinylive.io/py/examples/#static-content). In short, when you call `shiny.App`, you want to pass a directory as a `static_assets` argument.

The code:

```py
from pathlib import Path
from shiny import App, render, ui

app_ui = ui.page_fluid(
    ui.row(
        ui.column(
            6, ui.input_slider("n", "Make a Shiny square:", min=0, max=6, value=2)
        ),
        ui.column(
            6,
            ui.output_ui("images"),
        ),
    )
)


def square(x: ui.TagChildArg, n: int) -> ui.Tag:
    row = ui.div([x] * n)
    return ui.div([row] * n)


def server(input, output, session):
    @output
    @render.ui
    def images() -> ui.Tag:
        img = ui.img(src="logo.png", style="width: 40px;")
        return square(img, input.n())


www_dir = Path(__file__).parent / "www"
app = App(app_ui, server, static_assets=www_dir)
```

**Comment by ZihuiWang1** [comment]
Hi,
Thanks for the reply, however, my images are not pre-existing files (and they are dynamic) so I can't really use the `static_assets` argument. Is it possible to indicate a directory within the `server`?

**Comment by wch** [comment]
I'm not sure exactly what you want to do. Is it that you want to dynamically generate the images with, say, a `render.image`? Is there a particular reason you need to use an index.html instead of normal Shiny ui? If you can describe what you're trying to achieve overall, that would be helpful.

**Comment by ZihuiWang1** [comment]
Hi,

I am using py-shiny to display the prediction of a pre-trained ML model. With a given input, the ML program will do the prediction and generate a set of images along with a html file that includes description (text) and arrangement for each image in a UI. It would be great if I could incorporate the html file into shiny UI. Otherwise, I'll have to figure out a way to pair the text and image, and display them in a proper order, but the problem is that the number of text/image also vary depending on input.

Hope the description is clear and thank you for your time.

**Comment by wch** [comment]
Here's an example I came up with that seems similar to what you're describing. The app is relatively small but there's a lot going on. Note that `static_assets` is actually used to serve up the PNGs.


[Live example here](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACVKMgCwBsBLAIye4xUxOmSYAFNuwA6EWYOGimMNqk7EyPXlmxqNTKAGcWnMrNn1GTQ+24RsAoSLEBBdHiYBJCKgCuZQw8AeX8-AI8AZThDQ25SDzo4KEIybgA3OATKABM4Og9fbnMIQSgAc2iAfWzuOiYAXgkpAApKyppuTjg2gEosKETyJgB6JmkwUorDcfkaJgh9Saqaugw4AA9uQwDmnsRZJkPHcuXajBgAaxXd4rRUSsKGpkL+ivbOQuzmg6OXuzDKoYeLk6N9IOMPOMAHK+GC8PJMYhzYR2AIQpgAZg8ACYAAweACMuJ6eB+hz+Pn8lWSqVIlV4-jIpDBFQgeTYcHR4wA4pR2RR5nAAO4sE7jElk57cDDEUJUwpgkhyMASiA9YqyXJzQx5DKg-7+RBeSnhRFyshGkJkMKBazRWKkI1RGJxNX7CBHJgAAUSNPScAwAFEaDQ4ClJT6kil-WsMuRmgayBhWfy4OqPUctUxKrt3Z7PazKktKqwKgmTRgILsPEtDNVaumI7Lrf4I4MQRhCm2o6kMrHKGRy2Fk3y6Bz056s0rc5LPULuBxEahKAmVFN63VRuM7Ll1hh2GQYJwuWA6OKDMYD0fDHn83er5xAWQ6HYyk8H4YML6vhO70xEmQvh0B6LwABIACoALIADLNA+T4vhAZSNnI0DoE8bioM0dwPNwHg6nQer4WQbDcIQ1IxHAAT1LWG4obIADETC8myY4ClAgoijuGz7oenAGBA2RMFgSFMB0XTTIJcBzIWxalnAzQQEaqIeM2KxGpIHB7JK86LsQy5VmptQjGMExSXuD4nkK55GEwH63vefGfkKL4UN8GZ-kcNAzGAMwefmAA8NRpAAfLOgWCG+hh0IQ9QAORLCAEAAL4ALQEiJZRxSMYX+XeAWRdYMXxYlKWpdimXZcMuWeQFwzBTVf4+X5nkoZ5ahJh0ZRAQpv53h1GCGIQbAUKCPDbM0Y5IQpaokkw42DlNZazX1+YDYYUAZF1zRGZuYnbmucBJWlGWoEh4rhYcA2EOoOo3Kh7WmBgXU9fdj1JkNI15M0C2TVA02KT0c2-UtCnpR4qWKUwADUTAEnN6VA6tnrrZt0ncGUO3+CsJneRMh3HeVmUXXlRzXbdvWyGAyUALpAA)


```py
from pathlib import Path

import matplotlib.pyplot as plt

from shiny import App, Inputs, Outputs, Session, reactive, render, ui

images_dir = Path(__file__).parent / "images"
if not images_dir.exists():
    images_dir.mkdir()

app_ui = ui.page_fluid(
    ui.input_slider("n", "Number of points", 3, 20, 10),
    ui.input_action_button("generate", "Generate new page"),
    ui.output_ui("con"),
)


def server(input: Inputs, output: Outputs, session: Session):
    @reactive.Effect
    @reactive.event(input.generate)
    def _():
        gen_image_page(input.n(), images_dir)

    @output
    @render.ui
    @reactive.event(input.generate)
    def con():
        with open(images_dir / "index.html", "r") as htmls:
            html_string = htmls.read()
        return ui.HTML(html_string)


app = App(app_ui, server, static_assets=images_dir)


# Generate a new index.html and .png files
def gen_image_page(n: int, outdir: Path):
    # Generate an HTML file
    with open(outdir / "index.html", "w") as htmls:
        htmls.write(
            f"""
        <div>
          <img src='image{n}-1.png' />
          <img src='image{n}-2.png' />
        </div>
        """
        )

        # Generate some PNGs
        plt.figure()
        plt.scatter(list(range(n)), list(range(n)))
        plt.savefig(outdir / f"image{n}-1.png")
        plt.close()

        plt.figure()
        plt.scatter(list(range(n)), list(range(-1, -(n + 1), -1)))
        plt.savefig(outdir / f"image{n}-2.png")
        plt.close()
```

**Comment by ZihuiWang1** [comment]
Hi,
It works well!! Thank you very much for the solution. By the way, I set the `images_dir` to a temporary fold to avoid the accumulated images taking up too much space.
