### ISSUE TITLE
Documentation: example of failed download actually downloads the file.

### ISSUE THREAD

**Issue by OksanaBash** [rstudio/py-shiny#443]
Hi and thank you for the package:) 

I have noticed that example 4 ('Failed downloads') on the documentation page of Session.download decorator: https://shiny.rstudio.com/py/api/reference/shiny.Session.download.html#shiny.Session.download
instead of raising an error and not proceeding with downloading anything as described, downloads a "failuretest.txt" file with content "helloAn internal server error occurred". It is inconsistent with the expected behavior... 

I looked into this example since I would like to be able to abort the download in case some condition is not met and proceed with the download if the condition is met, but there seems to be no way to achieve this from the example page.

**Comment by wch** [comment]
Hi, I have a potential fix in #447. If you use a normal (non-streaming) download, you won't run into this problem, even without that potential fix.

A streaming download function is not `async` and does not use `yield`. For example, this is the function in the example app:

```py
    @session.download(id="download4", filename="failuretest.txt")
    async def _():
        yield "hello"
        raise Exception("This error was caused intentionally")
```

You would want to replace it with something like this:

```py
    @session.download(id="download4", filename="failuretest.txt")
    def _():
        if x:
            return "hello"
        else:
            raise Exception("This error was caused intentionally")
```
