### ISSUE TITLE
Call back the input in for loop

### ISSUE THREAD

**Issue by loankimrobinson** [rstudio/py-shiny#466]
I have the input "remove_{i}", i is count() when the users click to save object. Then I want to access the  input.remove_{i}() to remove the object by the user, but I have a hard time to call it back. I tried many way btn = eval('f"input.remove_{i}{()}"'), btn = f"input.remove_{i}{()}", but nothing work. Do you have any idea?

```
    @render.text
    def remove() -> str:
        if count() > 0:
            for i in range(1, count() + 1):
                # btn = eval('f"input.remove_{i}{()}"')
                # btn = f"input.remove_{i}{()}"
                btn = input.remove_1() # test it works for i = 1
                if btn > 0:
                    return("remove_" + str(i))
```

**Comment by jcheng5** [comment]
The way you would access this is with square brackets, e.g. `input[f"remove_{i}"]`.

Here's a [demo app](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACAMwFcJCzjiAbAM4AdCKLaNiMFoIAWNCNhZ0GzFgEF0eFo0oATOI20ca23VB40AbnFGi0qAPomWAXhYmsUAOZxHbfhM9AApRFnCPGgwFVA4yRwsyGlJHACM43ghQlD09YXwWfPVc-IBKYyiyH0EMPWtgmj1XfJJyKAVDMtFSuzEIAzYZQxtGBohYsm1iOIntQThBQWSIUsQwiIABc0sbDABRNjY4HnXwrbhE6zgMOBtyMYmMKFyeiAiWAZZnvUdBKThgqtTu92ExlMo3owoBBfMEAKxAt4g5GeBTzZjOGihJHI3GRDBVbw1OpWbF48kRVHjOKOCgADzIwTY+RiNJANAAvvltAA5UhwbSofgWOCyAQGRiuZlgABiNDg-D0LHZXLA5WBFJRUVZ8UuKXSZEyTPyuhgxBsjhV3MKYAASnAzTYyngNZr3p5UqN1Ti3SDGlKWqQqh1GJbOdzXb6WIRhYtHM0wDBsABaADMLBwaYjPrd3qj4XyAGJWsGIJ18JHyflUnA2Ew4Ht+tnc703YWWAAJKA2Fi8DNxXuyODR8xJUgsYiDMjyQQQr5DVBQKEUdhcSykbQ1whQDjzSvvdvT4c0Fj8PioFhWJc0KCpfjH2cQYisQRQI694geebsSTSKAsMtBAoJVOG4McIAAbn3CJ2wABWwadxz0YgFggAByVgyFHec60YZMz2IC9UmIPQlCgWd-3mRdl2HQQSFQAUZE-KB+H4aDwnbQDgNXMDllnacoFYXQjkYD9wQAd2mRUJwgfglHmYcj3YBQWMvFiOFsHNcXbScWAAFgwdiRwuChHFNc0-FkaE9HvUYdW0GhXl6T5CFHPxzItKz+lsh44gcxF3nOS5dgOI4Th9IKdmuW5KEZHVgGlDy-CtMAAF1XneT5HEBNYtPCTwksxY0wGLIN2jLUMUqcvoHDcDR0GCBxMTmYZDFeMAOVSoA) in Shinylive that demonstrates this:

**Comment by loankimrobinson** [comment]
Yeah, thanks.
