### ISSUE TITLE
plots not rendering when app is run in the browser from terminal-executed script

### ISSUE THREAD

**Issue by schackartk** [rstudio/py-shiny#473]
Hello,

I am so excited to see Shiny for Python!

Unfortunately, I am having some problems getting plotnine plots to render in a Shiny app that is initiated from the command line and displayed in the browser.

## Code

I have the following Python script called `example_app.py`:

```python3
#!/usr/bin/env python3

import pandas as pd
from plotnine import aes, geom_col, ggplot
from shiny import App, render, ui

app_ui = ui.page_fluid(
    "The plot should be right below this text:",
    ui.output_plot("plt"),
)


def server(input, output, session):
    @output
    @render.plot()
    def plt():
        df = pd.DataFrame(
            {
                "variable": [
                    "gender",
                    "gender",
                    "age",
                    "age",
                    "age",
                    "income",
                    "income",
                    "income",
                    "income",
                ],
                "category": [
                    "Female",
                    "Male",
                    "1-24",
                    "25-54",
                    "55+",
                    "Lo",
                    "Lo-Med",
                    "Med",
                    "High",
                ],
                "value": [60, 40, 50, 30, 20, 10, 25, 25, 40],
            }
        )
        df["variable"] = pd.Categorical(
            df["variable"], categories=["gender", "age", "income"]
        )
        df["category"] = pd.Categorical(df["category"], categories=df["category"])

        return ggplot(df, aes(x="variable", y="value", fill="category")) + geom_col()


app = App(app_ui, server)

app.run()

```

This code was taken nearly verbatim from the issue https://github.com/rstudio/shinylive/issues/29, with 3 changes:

- The shebang line (`#!/usr/bin/env python3`) was added to make it easier to execute
- A short string at the top of the ui page to ensure that I am viewing the app properly
- The `app.run()` command to get it to run on my browser

## How I am running it

I have enabled the executable bit:

```sh
$ chmod +x ./example_app.py
```

Then, at the terminal I am running:
```sh
$ ./example_app.py
```

I then ctrl+click the address it gives me, and the app is opened in my Firefox browser.

## Current behavior

The script runs, I open the app in my browser, and I see the text. No plot is rendered. No error message is displayed. See the image below:

<img width="287" alt="no_plot_app" src="https://user-images.githubusercontent.com/46572317/236084552-b0e759a5-07e9-41d8-9911-e444cbcbb816.PNG">

## Expected behavior

The app should have the text "The plot should be right below this text:" followed by a stacked barchart. It should be the same as what is provided in https://github.com/rstudio/shinylive/issues/29 (*i.e.* [this app](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFV8BQpqigRpUFkwPbpq1fUbaANsTIQucXv0HCA5q9Q2yEqHBYTXOEYAfRIrM2h0YKUmAF4mJSwoQOCaKyVpAApVJlyEjgxiBTJUYuDPW2ywTzJlMABKPFV6iNVZGlY5ADc5TK5S7yYikuKJFj8WDlJ6xBy8gAFhgbnc+ak9OSwvTJaIPKZ26zId2b39vOkO+NRpDAARKDIoADE6WDhss-PzkBXv-7qXSgdA4UAARlY4HVEExgH9-gimHVAhs6HUml9EQjkTI5Oj4VjznVklD8ATCXliYF8ZiKfsqaSMXSAWAuCR4DTmd86mzGIzyXSeRB2fzaVyhSLOVyALpM8VER5wVyCbDQ2ECil1Z5wGBQSFSrmUsAAWT1osN9LAAEYALQAJgALAaLXU7QBWG1up1ksXMuput0AamdhrqABliCH5RGbca4KYfRajXGE3Kk3UABIcVxsKNY2UallA9KkmHAABsAAYJA7q0w3XWAMx1u11q0tt0Sd01ysF33nAC+At2CMucLAQJB4P1YGlcRMGAAworlSDCHrPhSx4DgaCIaTZUx1xRVxw-LFxyjZGj8EiUNTbxK+XVpcOBduFSeVS-5zclyvBA4dcrEyD9jyVb9ZwkcDT3PMCALoVVZ12AUpDIBQ6D2dwKmOS4fD8TIAA9Yh3Kd93RJhsBIic9QURkmBoDgrCsaiYMg+p6iYQMmECEIwh2VpIlQecxFQTI0FQaIODGbo5F2MAB2lIA) on shinylive.io), since the code is (almost) the same.

## System information

- I am running on WSL2 connected to Ubuntu 20.04 kernel (this should not be an issue since I do indeed see the app output in my browser)
- Firefox v112.0.2
- Python v3.10.10
- shiny v0.3.2
- plotnine v0.10.0
- pandas v2.0.0

**Comment by schackartk** [comment]
## Other things I have tried

### Plot return

I have modified the code in `plt()` as

```python3
        plot = ggplot(df, aes(x="variable", y="value", fill="category")) + geom_col()

        return plot.draw()
```

### Browser

I have tried opening the app in Microsoft Edge.

## Results

Neither of the above changes yield a plot in the app.

**Comment by wch** [comment]
It works for me, running locally:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/86978/236095744-02a914c0-0263-4c2e-be8e-43ac9bed751d.png">

What version of plotnine do you have installed? Shinylive uses a development version of plotnine, and my local installation also has a dev version:

```
>>>  plotnine.__version__
'0.10.1.post98+g64295e1a'
```

The reason that shinylive uses this version of plotnine is because it uses some features that aren't in the current release version.

You can install the dev version with:

```
pip install git+https://github.com/has2k1/plotnine@main --upgrade
```

I've also been told that by @has2k1 that the new version of plotnine will be released next Monday.

**Comment by schackartk** [comment]
Thanks for the quick response. I was previously using plotnine v0.10.0. I tried again using the version you mentioned (0.10.1.post104+gb855157), but I am getting the same results.

I don't think it's a plotnine issue. I just tried a very basic app using matplotlib.pyplot ([this example](https://shinylive.io/py/examples/#app-with-plotl)). The input slider shows in the app, but no plot.

**Comment by wch** [comment]
Some questions:

- Are you able to produce matplotlib plots outside of Shiny? You could try running the example code [here](https://matplotlib.org/stable/gallery/lines_bars_and_markers/simple_plot.html).
- What version of matplotlib are you using?
- Have you tried launching it with `shiny run app.py` (and take out the call to `app.run()`)? For me the app works either way.
- If you use `App(app_ui, server, debug=True)`, what output does it produce?

**Comment by schackartk** [comment]
To your first point, it turns out I cannot generate plots at all unless in a Jupyter notebook.

Debugging this led me to this issue https://github.com/matplotlib/matplotlib/issues/22385. 

Adding:
```python3
import matplotlib

matplotlib.use('agg')
```

Fixes the issues. So it seems it's more to do with WSL2/matplotlib.pyplot/the display. I will continue reading through that issue to see if I can fix it through my system rather than in the app.

Thanks for your help, and hopefully this helps anyone else who runs into this!
