### ISSUE TITLE
Download .csv file

### ISSUE THREAD

**Issue by akins11** [rstudio/py-shiny#476]
First of all, I want to express my gratitude for bringing the shiny web application framework to python.

I have a question regarding how to download a Pandas Dataframe. Specifically, I am interested in using the `ui.download_button()` function and the `@session.download()` decorator to enable users to download the data in a csv file format.

```python

from shiny import App, ui, Inputs, Outputs, Session, reactive
from pandas import DataFrame


app_ui = ui.page_fluid(

    ui.download_button(id="download_data", label="Download")

)

def server(input: Inputs, output: Outputs, session: Session):

    @reactive.Calc
    def app_dataframe():
        return DataFrame({
            "color": ["Blue", "Yellow", "Red"],
            "price": [150, 213, 124]
        })
    

    @session.download()
    def download_data():
        pass


app = App(app_ui, server)

```

Can you please provide some guidance or examples on how to achieve this? I would greatly appreciate any help or recourses you can provide.

**Comment by GShotwell** [comment]
Thanks for the issue, here is a minimal example of a file download app. 

```
from pathlib import Path
from shiny import App, ui, render, reactive, Inputs, Outputs, Session
import pandas as pd
from pandas import read_csv

app_ui = ui.page_fluid(
    ui.download_button("download", "Download CSV"),
    ui.output_table("table"),
)


def server(input: Inputs, output: Outputs, session: Session):
    @reactive.Calc
    def ts_data():
        return read_csv(
            "https://gist.githubusercontent.com/slopp/ce3b90b9168f2f921784de84fa445651/raw/4ecf3041f0ed4913e7c230758733948bc561f434/penguins.csv"
        )

    @output
    @render.table()
    def table():
        return ts_data()

    @session.download(filename="data.csv")
    def download():
        yield ts_data().to_csv()


app = App(app_ui, server)
```

**Comment by akins11** [comment]
Thanks, I was able to implement your solution immediately, and it worked perfectly.

**Comment by remybonnav** [comment]
How did you solve it?
In my case if I use same code as @gshotwell  but in "def ts_data():" if I replace "return read_csv..."  by 
data={"a":[1,2,3], "b":[4,5,6]}
dF=pd.DataFrame(data)
return dF

then it does not work at all.

Any hints?

**Comment by remybonnav** [comment]
> Have you seen the reference page (especially the example section)? https://shiny.rstudio.com/py/api/Session.html#shiny.Session.download

None of the examples work when I apply to a pandas dataframe that we generate from scratch.

**Comment by Linhkust** [comment]
Hello, i am wondering how to download multiple files in a sequential manner.

**Comment by fgashakamba** [comment]
I am new to Python. I am rather an R user. I am only using python because my IT team asked me to port all my `shiny `apps to Python because this is the only way can host them.
I had the same issue: allowing the user to download a **dataframe** as a **CSV** file. I was using `return` and was getting errors. Now, using `yield` solved my issue. I don't know the difference between these two. I am going to read further.
**However, it got me thinking: could this be a solution to downloading a `geodataframe` as a `geopackage` file as well?**
This has puzzled me for the last two days.
