### ISSUE TITLE
Pooling database connections

### ISSUE THREAD

**Issue by cvmartin** [rstudio/py-shiny#482]
This is related to:
- Usage of global variables ([this](https://github.com/rstudio/py-shiny/issues/469) issue)
- Alternatively: how to run `shiny.App` with arbitrary parameters passed onto `app_server`.

---

As as user of R Shiny, I’ve been using in the past the package `pool` , both in a single file (as specified [here](https://shiny.posit.co/r/articles/build/pool-basics/)) and setting the pool in a `global.R` file.

The intention was to instantiate a connection pool per application, and then let each R session use a connection from this pool. It worked as expected, because as specified [here](https://shiny.posit.co/r/articles/improve/scoping/), objects in `global.R` are “loaded into the global environment of the R session; all R code in a Shiny app is run in the global environment or a child of it”.

Back to Python: in [issue 469](https://github.com/rstudio/py-shiny/issues/469) it was specified that Shiny Python does not have an equivalent mechanism to `global.R`. Indeed I’ve tried several approaches to instantiate a pool connection (I am using [MongoDB](https://pymongo.readthedocs.io/en/stable/api/pymongo/pool.html), but it could also be [postgres](https://medium.com/@dipan.saha/python-connection-pooling-a72356a04e53#:~:text=Here%20are%20some%20best%20practices%20to%20keep%20in,...%205%20Be%20mindful%20of%20connection%20timeouts.%20)) and use it inside server code, but nothing seems to work. And if I have code like:

```
def run_app():
    app = App(app_ui, app_server)
    app.run()
```
`app_server`, of type `Callable[[Inputs, Outputs, Session], None]`, does not accept any additional, arbitrary inputs.

If `app_server` could behave like the server side of a module, allowing additional parameters, the code could perhaps look like:
```
def run_app():
   postgres_pool = psycopg2.pool.SimpleConnectionPool(
      # arguments to connect ...
   )

   app = App(app_ui, app_server(connection_pool=postgres_pool))
   app.run()
```

And `connection_pool.getconn()` would be executed inside the `app_server` code.

Is there currently a way to achieve this behaviour pooling connections?

Thanks in advance.

**Comment by j-carson** [comment]
I'm not sure how to get from the Shiny App to the underlying Starlette App, but if you can get that, you can store your pool in app.state (see https://www.starlette.io/applications/#storing-state-on-the-app-instance). Starlette App objects have startup and shutdown methods to spin up and spin down your pool as well.

**Comment by wch** [comment]
If I understand your question, I think this should answer it.
You can use the normal Python scoping rules along with the way that Shiny runs the `server` function when users connect.

With Shiny, each user session (that is, each browser window pointed at the app) causes the `server` function to execute, so variables created inside that function are scoped to that session. However, variables created _outside_ of the server function are shared across all sessions.

For example, here is how you could share a value named `global_value` across multiple users connected to the same app:

```py
from shiny import App, reactive, render, ui

global_value = 100


app_ui = ui.page_fluid(
    ui.input_action_button("inc", "Increment shared global value"),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):
    @reactive.Effect
    @reactive.event(input.inc)
    def _():
        global global_value
        global_value += 1

    @output
    @render.text
    @reactive.event(input.inc, ignore_none=False)
    def txt():
        return f"global_value is {global_value}"


app = App(app_ui, server)
```

Note that for simplicity, the global variable was not reactive.

But you could use a `reactive.Value` or `reactive.Calc` and have it be reactive across sessions, as shown here. This way when you click on the button in one session, it causes the text output to increment in all active sessions.

```py
from shiny import App, reactive, render, ui

global_value = reactive.Value(100)


app_ui = ui.page_fluid(
    ui.input_action_button("inc", "Increment shared global value"),
    ui.output_text_verbatim("txt"),
)


def server(input, output, session):
    @reactive.Effect
    @reactive.event(input.inc)
    def _():
        global global_value
        global_value.set(global_value() + 1)

    @output
    @render.text
    def txt():
        return f"global_value is {global_value()}"


app = App(app_ui, server)
```



https://github.com/rstudio/py-shiny/assets/86978/170a0c84-a4e4-497d-905d-e567167d6d3c

**Comment by cvmartin** [comment]
Thanks a lot for your replies. I think I will go for the option indicated by @j-carson which, in its simplest form and in pseudocode what works for me is something like

```
app = App(app_ui, app_server, static_assets=get_statics_assets_dir())
app.starlette_app.state.POOL_CONNECTION = postgres_pool
app.run()

# and inside `app_server`
postgres_pool = session.app.starlette_app.state._state["POOL_CONNECTION"]
```

I think this simplifies the scoping in my case, having independent dedicated files for `app_ui` and `app_server`. And the possibility of setting an`app.starlette_app.on_shutdown` is particularly good to close the connection pool.

Thanks also to @wch for explaining that it is possible having `reactive.Value` and `reactive.Calc` shared across sessions! I thought these were only possible defined inside the server side.
