### ISSUE TITLE
Feature request: Include stopApp functionality

### ISSUE THREAD

**Issue by vnijs** [rstudio/py-shiny#490]
R-shiny has an option to `stopApp`. Py-shiny has `session.close()` but that doesn't stop the running server process. Is there a way for a user to stop the running server process? 

Thanks

```python
@reactive.Effect
@reactive.event(input.stop, ignore_none=True)
async def stop_app():
    await session.close()
```

**Comment by wch** [comment]
Does it work to do `session.app.stop()`?

**Comment by vnijs** [comment]
Thanks for the suggestion @wch. Both `session.close()` and `session.app.stop()` seem to do the same thing, i.e., close the connection. However, they don't stop the server process. "Shutting down" doesn't happen until you use Ctrl-C in a terminal or you interrupt the process running inside a jupyter notebook cell.

See example below adapted from https://github.com/rstudio/py-shiny/issues/403

```python
from shiny import App, render, ui, reactive, Inputs, Outputs, Session
import uvicorn
import asyncio
import nest_asyncio
import webbrowser
import polars as pl


class radiant_data:
    def __init__(self, dataset: pl.DataFrame) -> None:
        self.dataset = dataset

    def data_ui(self):
        return ui.page_fluid(
            ui.output_table("show_data"),
            ui.input_action_button(
                "stop",
                "Stop app",
                class_="btn-danger",
                onclick="window.close();",
            ),
        )

    def data_server(self, input: Inputs, output: Outputs, session: Session):
        @reactive.Calc
        def load_data():
            return self.dataset

        @output(id="show_data")
        @render.table
        def show_data():
            return load_data()

        @reactive.Effect
        @reactive.event(input.stop, ignore_none=True)
        async def stop_app():
            await session.app.stop()


def launch(data):
    # need to ensure the process is stopped
    rd = radiant_data(data)
    config = uvicorn.Config(App(rd.data_ui(), rd.data_server), port=8000)
    server = uvicorn.Server(config)
    loop = asyncio.get_running_loop()
    loop.create_task(server.serve())
    webbrowser.open("http://127.0.0.1:8000")


def launch_nest(data):
    # locks interactive session
    rd = radiant_data(data)
    nest_asyncio.apply()
    webbrowser.open("http://127.0.0.1:8000")
    uvicorn.run(App(rd.data_ui(), rd.data_server), port=8000)


mydata = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

# launch(mydata)
launch_nest(mydata)
```

**Comment by wch** [comment]
I think that Uvicorn expects to be the only task running in a Python process. Apparently there isn't a way to shut down Uvicorn programmatically: https://github.com/encode/uvicorn/discussions/1103

When you call `App.run()`, it calls `_main.run_app(self)`, which launches the app with `uvicorn.run()`. However, Shiny can be run on a ASGI server other than Uvicorn. (In Shinylive we actually don't use Uvicorn -- we simply implement enough of an ASGI server to run a Shiny app.)

You can launch an app with hypercorn instead, and it does support shutting down an application programmatically: https://pgjones.gitlab.io/hypercorn/how_to_guides/api_usage.html#graceful-shutdown

Here's a script that takes a simplified version of your app and runs it with hypercorn. If you click on the Stop App button, it will exit.

```py
import asyncio
import webbrowser

from hypercorn.asyncio import serve
from hypercorn.config import Config

from shiny import App, Inputs, Outputs, Session, reactive, ui

shutdown_event = asyncio.Event()


app_ui = ui.page_fluid(
    ui.input_action_button(
        "stop",
        "Stop app",
        class_="btn-danger",
        # onclick="window.close();",
    ),
)


def server(input: Inputs, output: Outputs, session: Session):
    @reactive.Effect
    @reactive.event(input.stop, ignore_none=True)
    async def stop_app():
        await session.app.stop()
        shutdown_event.set()


async def launch_app(port: int):
    webbrowser.open(f"http://127.0.0.1:{port}/")

    config = Config()
    config.bind = [f"localhost:{port}"]
    return await serve(
        App(app_ui, server),
        config,
        shutdown_trigger=shutdown_event.wait,
    )


# Launch two instances of the app, on ports 8000 and 8001.
async def launch_two():
    task0 = asyncio.create_task(launch_app(8000))
    task1 = asyncio.create_task(launch_app(8001))
    await asyncio.gather(task0, task1)


asyncio.run(launch_app(8000))
# asyncio.run(launch_two())
```

You can also uncomment the last line, and instead of `launch_app()`, call `launch_two()`, which will launch two instances of the app, one on port 8000, and one on port 8001. This is relevant to your issue #403. It shows that you can launch one or more apps without blocking.

So I believe that in a Jupyter notebook, you could call `asyncio.create_task(...)` from the top level to launch an app. (It would probably also be a good idea to keep track of running tasks in a list so that you can clean them up if necessary.)

**Comment by wch** [comment]
One more thing I should add: in my previous comment, the replacing of uvicorn with hypercorn is needed only if you want to be able to shut down the Shiny app without stopping the whole Python process, and that is what you'd want to do if you're running the Shiny app within a Jupyter notebook.

However, if you're fine with stopping the entire process, you could simply use `os.kill(os.getpid(), signal.SIGTERM)`:

```py
import os
import signal

from shiny import App, Inputs, Outputs, Session, reactive, ui

app_ui = ui.page_fluid(
    ui.input_action_button("stop", "Stop app", class_="btn-danger"),
)

def server(input: Inputs, output: Outputs, session: Session):
    @reactive.Effect
    @reactive.event(input.stop, ignore_none=True)
    async def stop_app():
        await session.app.stop()
        os.kill(os.getpid(), signal.SIGTERM)

app = App(app_ui, server)
```

And launch this the usual way, with `shiny run app.py`.

**Comment by vnijs** [comment]
Thanks @wch. The 2nd option actually works great for my app (see link below). The stop actionbutton now fully shuts down the server process but the notebook keeps working as before.

https://github.com/vnijs/pyrsm/blob/main/pyrsm/radiant/regress.py#L255-L282

The first option you suggested sounds like it would work really well for cases where the shiny app can run similarly to widgets embed in a jupyter notebook (https://github.com/rstudio/py-shiny/issues/403). I'm having an issue with my conda environment when trying to use hypercorn, however, so will need to take a closer look at that. For now, the 2nd suggestion works great so I'll go with that. Thanks again @wch!

```
from wsproto.handshake import handshake_extensions
ImportError: cannot import name 'handshake_extensions' from 'wsproto.handshake' (/opt/conda/lib/python3.10/site-packages/wsproto/handshake.py)
```
