### ISSUE TITLE
Shiny Python app deployment on shinyapps.io error: Bundle does not contain manifest file (package)

### ISSUE THREAD

**Issue by Giulia-Sarti** [rstudio/py-shiny#494]
Hi, 
I have a Windows and when i try to deploy my app on shinyapp.io an error occurs. In particolar the error is:

"Error: Application deployment failed with error: Unhandled Exception: Child Task 1301926936 failed: Error parsing manifest: Bundle does not contain manifest file: demo\Lib\site-packages\Jinja2-3.1.2.dist-info\INSTALLER"

in the folder "demo\Lib\site-packages\Jinja2-3.1.2.dist-info" there is the file INSTALLER, so i don't understand the issue.

Thanks,

**Comment by wch** [comment]
Hi, this is probably the same issue as: https://github.com/rstudio/rsconnect-python/issues/373

**Comment by wch** [comment]
I believe this was fixed by https://github.com/rstudio/rsconnect-python/issues/373.
