### ISSUE TITLE
Issue with shiny as a conda dependency

### ISSUE THREAD

**Issue by vnijs** [rstudio/py-shiny#508]
Adding shiny as a pip dependency has worked fine (https://pypi.org/project/pyrsm/). For some reason, however, I keep running into issue with conda. Whether I use shiny 0.2.9 or 0.3.3 the build process (output below) keeps saying that the shiny module is not available. 

Question: Do you know of any other python conda libraries that have listed shiny as a dependency? Are you planning to keep the conda version up to date with the pypi version? Thanks

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=710328&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=996

pypi set up file: https://github.com/vnijs/pyrsm/blob/main/setup.cfg

**Comment by jcheng5** [comment]
I didn't realize they had gotten so far out of sync. We're working on getting this resolved. Thanks for the heads up!

**Comment by jcheng5** [comment]
Sorry it took so long to resolve this, we didn't even have permissions to make the needed changes. Should be all set now, and our release process now includes conda updating so it shouldn't get out of sync going forward.

Thanks Vincent!
