### ISSUE TITLE
Add `options` argument for input_selectize

### ISSUE THREAD

**Issue by vnijs** [rstudio/py-shiny#509]
I noticed in py-shiny `input_selectize` doesn't have the `options` argument. Would be great to have that. Thanks.

https://shiny.posit.co/r/reference/shiny/1.7.4/selectinput

**Comment by nealrichardson** [comment]
What's missing here is the logic in the R `selectizeIt()` function: https://github.com/rstudio/shiny/blob/main/R/input-select.R#L124-L126

**Comment by nealrichardson** [comment]
Turns out this is a duplicate of #158
