### ISSUE TITLE
Dynamic Rendering of MathJax and/or Re-typeset button?

### ISSUE THREAD

**Issue by jrgrohs** [rstudio/py-shiny#522]
I apologize if this is a simple issue that is solved elsewhere. The application I've been working on uses rendered math and sympy. I found MathJax header information to use via the featured "Regularization" app in examples and that got things mostly working for me. But, I'm wondering if there is a quick easy way to re-render math dynamically (i.e., re-typeset https://docs.mathjax.org/en/latest/advanced/typeset.html) or upon reactive event or reactive effect -- for example, clicking a button and re-typesetting the app to notice the user input math via the simple text input such as $$ x+y=5 $$.

Thanks!

**Comment by GShotwell** [comment]
Would this be solved by a general markdown output option? Something like:

```
    @output
    @render.md
    def math():
        out = f"""
                $$
                Pr(A) = {input.p_a()} \\
                Pr(B) = {input.p_b()}
                $$
              """
        return out
```

**Comment by jrgrohs** [comment]
Ok - no button needed. A simple return statement like this works at the end of @output @render.ui 
return [ui.panel_well(ui.markdown(my_math_string),
                ui.tags.script("if (window.MathJax) MathJax.Hub.Queue(['Typeset', MathJax.Hub]);"))]
