### ISSUE TITLE
Incorrect link in `download_button` and `download_link` examples

### ISSUE THREAD

**Issue by datakid** [rstudio/py-shiny#555]
I thought I was going crazy in issue https://github.com/rstudio/py-shiny/issues/554 - and I was wrong in that issue. 

Both of the below links have a link to an outdated blob:

```
# For more examples of different types of download handlers, see:
# https://github.com/rstudio/py-shiny/blob/68ffc27/examples/download/app.py#L90
```

That blob is at `py-shiny/examples/download/app.py` but a more contemporary codebase has those examples at `py-shiny/shiny/examples/download/app.py`

Here are the links to the outdated code:

https://github.com/rstudio/py-shiny/blob/f45df58952d9362b83d53934474a0685dac9477a/shiny/examples/download_button/app.py#LL14C1-L14C80

https://github.com/rstudio/py-shiny/blob/f45df58952d9362b83d53934474a0685dac9477a/shiny/examples/download_link/app.py#LL14C3-L14C80

**Comment by nealrichardson** [comment]
Thanks for catching this. Would you be interested in submitting a PR to fix it?
