### ISSUE TITLE
Agreement for Pull Requests has old company name

### ISSUE THREAD

**Issue by datakid** [rstudio/py-shiny#558]
I was just sent an email by GH about the `RStudio Corporate and Individual Contributor Agreement` which is using an incorrect company name afaict. See screenshot:

![Screenshot 2023-06-08 161912](https://github.com/rstudio/py-shiny/assets/97304/0ce70d68-1ad5-4fea-b30c-a261c6971c2f)

**Comment by nealrichardson** [comment]
Thanks for reporting. I've opened an internal IT ticket to fix this.
