### ISSUE TITLE
In dev version, value boxes in penguins app have incorrect layout

### ISSUE THREAD

**Issue by wch** [rstudio/py-shiny#563]
I believe these three value boxes should be in a row.

![image (24)](https://github.com/rstudio/py-shiny/assets/86978/db9004ea-7ef6-4862-898d-518b077cba13)

**Comment by jcheng5** [comment]
@schloerke I'm not seeing this particular problem anymore, but I do see scrollbars in the value boxes

<img width="1146" alt="image" src="https://github.com/rstudio/py-shiny/assets/129551/3f75f98c-d219-4e4a-a668-f2f9f41483ba">

**Comment by schloerke** [comment]
Yes. @karangattu saw this as well. 

I'll be looking at it in a PR with other small fixes

**Comment by jcheng5** [comment]
Great, thanks. Also, I had originally designed this for `x.ui.page_fillable`, I noticed it's now `ui.page_fluid`. If that was intentional, fine, but I thought it worked well when it filled the page.

**Comment by schloerke** [comment]
Ah. I was trying to minimize the `x` usage for pages. But this app uses it anyways, so I'm ok to use more methods.

Should we use `x.ui.page_sidebar()` (which calls `x.ui.page_fillable()`) to simplify the API?

**Comment by schloerke** [comment]
![Screenshot 2023-06-21 at 3 05 37 PM](https://github.com/rstudio/py-shiny/assets/93231/d933a8c1-5dae-4381-b5b2-b9b1e04c65e9)

Yup. Going to use `x.ui.page_sidebar()`

**Comment by schloerke** [comment]
Valuebox layout problem was fixed with [shinyswatch 0.2.4](https://github.com/rstudio/py-shinyswatch/blob/v0.2.4/CHANGELOG.md#024---2023-04-18)
