### ISSUE TITLE
'in' Not working In panel_conditional

### ISSUE THREAD

**Issue by DRosenman** [rstudio/py-shiny#566]
Let's say I have an input 'state' that can contain multiple values. How do I check if the input state contains 'Alabama'. I assumed I could just use 'in' like this but it doesn't seem to work. It works using R shiny though:

```
from shiny import ui, App, render

app_ui = ui.page_fluid(
    ui.input_selectize("state", "State", choices = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming", "Washington D.C."
],  multiple = True),
ui.panel_conditional("'Alabama' in input.state", "TEST")
       
)


def server(input, output, session):
    ...
app = App(app_ui, server)
```

**Comment by DRosenman** [comment]
Actually I figured out how to do it!

```"input.state.some(r => ['Alabama'].includes(r))"```

This works:
```
from shiny import ui, App, render



app_ui = ui.page_fluid(
    ui.input_selectize("state", "State", choices = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming", "Washington D.C."
],  multiple = True),
ui.panel_conditional("input.state.some(r => ['Alabama'].includes(r))", "TEST"),

)


def server(input, output, session):
    ...
app = App(app_ui, server)
  ```

**Comment by wch** [comment]
Great that you figured it out! As I'm sure you know now, the condition is JavaScript code, not Python.

You should actually be able to simplify it to:

```
    ui.panel_conditional("input.state.includes('Alabama')", "TEST"),
```

[Shinylive example here](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMArhzxMAgugl1KAEzh0AOhFVpUAfTFMAvKI5YoAcziaaAGzHyAFKqYODRiHAuaSEeRzIdSUC3ZgXKgiZBgsZFAUGFyEVoosNgDkkhZQAEawUEkAlMr4TPkAKgCiAMpF+Tl49o5iMRAhZJosrnCEPgBecHYQjv2FYBFRcPk1fQMO+WWRFGO1k4RsxByEcCy6wAuTjvmpGVnzEzu7YPssANZQRyf9e3QcnX43t1NndFcQLFAsL6-5AGF-BwaIIIBxrvhtidAcQLIIoPJiH9brCIC4OqtQiiYWAACKuKAAdygchxO3yADF4Q95JDxq83gBxOCCYwQ8mTfIACWJUA4HE5A3yAEk6cshXcwCKLBYuCtflDjqjpZ4IdBJacRcQSZq3gBpKBfH56wb6yhkESEC7YU35AAyxDELHV9OhFLAAFl+S47V7Sdg0p4-d6WN8liJWmQyIqGYz8p7VpxjEaQ1wXCxiJE02GOLn0IKlYzBomw06HiHSJENUX42AAHJwdJ0H5XP2NgBuiLdytxjaJTF5-HYHDJtf+DbgA4AUkpWrbxyr+0xPXAAB6rZGLvtTpgATUEF3bgjIbCYQIYcprcYn9ZPZ7xUAuWZ7xfyAHlOFubyr3xc0ssMCvnW75yMYpB+gACpQXyBl24LAROABKyyKEwIosEG8h+mUTqnuepJwlwiEqrhoQPk+L5+kUMHrK0ozbh6NFriajFcmAACqkRsH6ABqSgwFWfGjuyCF+gA6j8nAQMYZAQWxwpgOJ6zCLxIlcByClSuJeYeC6ahaac4nYIwXDGBJUlmXJfR4hgAIYEKAC6P79DAIgWD4qAWHAuhFHQIhwD+1SqHkahhRoehSOgNgaNo4hMHeLihWAAC+jlAA)
