### ISSUE TITLE
Dynamic Creation of Tabs

### ISSUE THREAD

**Issue by jrgrohs** [rstudio/py-shiny#576]
I apologize - I think this is already being worked on (#499) but I can't quite tell from the dynamic_navs branch if it enables the specific functionality I am looking for or not.  I'm trying to have a navset_tab_card that is dependant on what boxes are checked from a input_checkbox_group (actual use case is displaying tabs for each equation selected from an equation bank).  

So, essentially like this example program copied below except that I only want the respective dynamic tabs (A,B,C,D) shown once they are checked off in the checkbox. In this example they are displayed all the time.

Thanks in advance!

---

```
from shiny import App, render, ui

tab_bank = {
    "Tab A": "Tab A",
    "Tab B": "Tab B",
    "Tab C": "Tab C",
    "Tab D" : "Tab D"
}

app_ui = ui.page_fluid(
        ui.row(
            ui.column(8,ui.output_ui("dyn_ui_nav")),
            ui.column(4,
                ui.navset_tab_card(
                    ui.nav("Tab Bank",
                        ui.input_checkbox_group("selected_tabs","Choose your tabs:",tab_bank,
                        ),
                    ),
                ),
            ),
        ),
)

def server(input, output, session):
    @output
    @render.ui
    def dyn_ui_nav():
        tabs = ui.navset_tab_card(
                ui.nav(
                    "Static Tab",
                    ui.markdown("Static Text Here Giving Instructions")
                ),
                ui.nav(
                    "Tab A",
                    ui.input_numeric("Tab_A","Input:",1,min=1,max=5)
                ),
                ui.nav(
                    "Tab B",
                    ui.input_numeric("Tab_B","Input:",2,min=1,max=5)
                ),
                ui.nav(
                    "Tab C",
                    ui.input_numeric("Tab_C","Input:",3,min=1,max=5)
                ),
                ui.nav(
                    "Tab D",
                    ui.input_numeric("Tab_D","Input:",4,min=1,max=5)
                )
            )
        return tabs


app = App(app_ui, server)
```

**Comment by jrgrohs** [comment]
This is sort of a brute force inelegant solution but will better demonstrate the functionality I think would be nice.

```
from shiny import App, render, ui

tab_bank = {
    "Tab A": "Tab A",
    "Tab B": "Tab B",
    "Tab C": "Tab C",
    "Tab D" : "Tab D"
}

app_ui = ui.page_fluid(
        ui.row(
            ui.column(8,ui.output_ui("dyn_ui_nav")),
            ui.column(4,
                ui.navset_tab_card(
                    ui.nav("Tab Bank",
                        ui.input_checkbox_group("selected_tabs","Choose your tabs:",tab_bank,
                        ),
                    ),
                ),
            ),
        ),
)

def server(input, output, session):
    @output
    @render.ui
    def dyn_ui_nav():
        tab_keys = input.selected_tabs()
        print(input.selected_tabs())
        #req(tab_keys)
        lookup_tabs = [tab_bank[key] for key in tab_keys]

        dynamic_tabA = None
        dynamic_tabB = None
        dynamic_tabC = None
        dynamic_tabD = None
        
        if "Tab A" in tab_keys:
            dynamic_tabA="Tab A"
        if "Tab B" in tab_keys:
            dynamic_tabB="Tab B"
        if "Tab C" in tab_keys:
            dynamic_tabC="Tab C"
        if "Tab D" in tab_keys:
            dynamic_tabD="Tab D"
       
        tabs = ui.navset_tab_card(
                ui.nav(
                    "Static Tab",
                    ui.markdown("Static Text Here Giving Instructions")
                ),
                ui.nav(
                    dynamic_tabA,
                    ui.input_numeric("Tab_A","Input for Tab A:",1,min=1,max=5)
                ),
                ui.nav(
                    dynamic_tabB,
                    ui.input_numeric("Tab_B","Input for Tab B:",2,min=1,max=5)
                ),
                ui.nav(
                    dynamic_tabC,
                    ui.input_numeric("Tab_C","Input for Tab C:",3,min=1,max=5)
                ),
                ui.nav(
                    dynamic_tabD,
                    ui.input_numeric("Tab_D","Input for Tab D",4,min=1,max=5)
                ,
                )
        )
        
        return tabs


app = App(app_ui, server)
```

**Comment by GShotwell** [comment]
My solution to this would be the following. I think you're on the right track but the bit I think you missed is that whenever a shiny function takes `*args` or `*kwargs` you can pass a list to it This also illustrates a couple of good habits with Shiny:

1) Whenever you find yourself repeating UI code, it's worth extracting that code into a function. This is good both because it makes your code sturdier, but also because it tends to give you a clue as to how you should solve the problem. In this case extracting out the `numeric_tab` provides a clue that we want to iterate over the names and values of something.

2) When generating things it's usually a good default to store the results of the generation step in a list. In this case we're generating tabs so it's a good idea to generate them, stick them in a list or `htmltools.TagList` and then pass them to `navset_tab_card` at the end. 

```
from shiny import App, render, ui

tab_bank = {"A": "Tab A", "B": "Tab B", "C": "Tab C", "D": "Tab D"}

app_ui = ui.page_fluid(
    ui.row(
        ui.column(8, ui.output_ui("dyn_ui_nav")),
        ui.column(
            4,
            ui.navset_tab_card(
                ui.nav(
                    "Tab Bank",
                    ui.input_checkbox_group(
                        "selected_tabs",
                        "Choose your tabs:",
                        tab_bank,
                    ),
                ),
            ),
        ),
    ),
)


def numeric_tab(name, value):
    return ui.nav(f"Tab {name}", ui.input_numeric(name, "Input:", value, min=1, max=5))


def server(input, output, session):
    @output
    @render.ui
    def dyn_ui_nav():
        tab_dict = {"A": 1, "B": 2, "C": 3, "D": 4}
        tabs = [
            numeric_tab(key, value)
            for key, value in tab_dict.items()
            if key in input.selected_tabs()
        ]

        static_tab = ui.nav(
            "Static Tab", ui.markdown("Static Text Here Giving Instructions")
        )

        tabs.insert(0, static_tab)

        tabset = ui.navset_tab_card(*tabs)
        return tabset


app = App(app_ui, server)
```

**Comment by jrgrohs** [comment]
Wow - thanks, this is immensely helpful. I didn't realize I could pass a list into the ui.navset_tab_card -- that is really a game changer.  I knew I must be missing something obvious. Thanks so much!

**Comment by jrgrohs** [comment]
One other note here. I'm going to work on a solution but in case anyone else has a quick elegant one. These methods end up dumping/resetting all inputs any time the checkbox changes.  For example, if adding tab B and changing the input in tab B, once tab C gets added, tab B automatically resets.  I understand why this is the case but solving it currently eludes me. I think the solution is something like having global start values for the different input features of any tab and then updating them while the tab is active but trying to implement that solution and it still keeps resetting. Will post again if I figure it out. Thanks!

**Comment by GShotwell** [comment]
Ah yes for that you probably want to use conditional panels.

https://shiny.rstudio.com/py/api/ui.panel_conditional.html

**Comment by jrgrohs** [comment]
Thank you - I'll look into that option. I originally started down that path as my first choice method but got stuck when there was an object type mismatch (conditional panel outputs as tags vs. ui.navs) but I will read/try more. Thanks for the help!
