### ISSUE TITLE
page_navbar Example: `navset_bar()` seems to be lacking a order unlike `navset_pill_card()`

### ISSUE THREAD

**Issue by karangattu** [rstudio/py-shiny#579]
Look at the example shown below in the screenshot

![app_py_—_py-shiny](https://github.com/rstudio/py-shiny/assets/4220325/d6ba3ee8-3553-4756-bfe1-5f46e552851c)

One has a border, the other one doesn't.
In my opinion, both the **navset** components should have a border

**Comment by gadenbuie** [comment]
I think this intentional. `navset_pill_card()` is intended to be a standalone component, but `navset_bar()` is intended to take the full space of its parent container – for example how it's used in `page_navset()`.

**Comment by karangattu** [comment]
Got it. Thanks for the clarification.
