### ISSUE TITLE
examples/dataframe/app.py does not work

### ISSUE THREAD

**Issue by Zak-Projects** [rstudio/py-shiny#587]
When trying to run examples/dataframe/app.py you receive the following error:

**AttributeError: module 'shiny.ui' has no attribute 'output_data_frame'**

Is there an attribute that replaced this?

**Comment by wch** [comment]
Do you have the latest version installed, 0.4.0?

**Comment by Zak-Projects** [comment]
Ahh that fixed it. Did not see that there was a release yesterday!
