### ISSUE TITLE
Move gallery apps to shinyapps.io

### ISSUE THREAD

**Issue by GShotwell** [rstudio/py-shiny#616]
We currently have a bunch of apps in the gallery deployed using shinylive. I did some tests and it seems that these apps take about 25s to load from a new browser session. This is pretty slow for such simple applications and since the user who's viewing the gallery likely doesn't know about the internals of shinylive they'll likely think "Shiny is slow" instead of "Pyodide is slow".

**Comment by nealrichardson** [comment]
Looks like #617 is the same

**Comment by GShotwell** [comment]
Whoops! Closing
