### ISSUE TITLE
Input for tabular data?

### ISSUE THREAD

**Issue by mdaeron** [rstudio/py-shiny#656]
I'm just scratching the surface of Shiny, so my question might have an obvious answer, but I wasn't able to answer it based on the [UI inputs API](https://shiny.posit.co/py/api/#ui-inputs).

Is there a canonical way to create a tabular input area where the user can directly paste data copied from a spreadsheet application? I'm thinking of something like [streamlit.data_editor()](https://docs.streamlit.io/library/api-reference/data/st.data_editor).

In my experience, there are countless ways in which users mess up when converting spreadsheets to comma- or tab-delimited data before pasting the result in a regular [input_text_area()](https://shiny.posit.co/py/api/ui.input_text_area.html#shiny.ui.input_text_area). An input for tabular data, even returning a list of lists of `str`, would be incredibly useful.

**Comment by jcheng5** [comment]
That doesn't currently exist but it's a great idea!

A data editor would be ideal, but I could imagine a stopgap where input_text_area could detect spreadsheet formats on the clipboard and do the conversion automatically. If you paste into the GitHub comment textarea, it does something like that (but to Markdown, not CSV/TSV).

**Comment by mdaeron** [comment]
> If you paste into the GitHub comment textarea, it does something like that (but to Markdown, not CSV/TSV).

Wow, I wasn't aware of that. Pretty cool.

**Comment by jcheng5** [comment]
Awesome, we're happy to have you here!

I just tried pasting from Numbers and Google Sheets into this [web clipboard inspector](https://evercoder.github.io/clipboard-inspector/) and it looks like there's not JSON or CSV data being put on the clipboard by those apps, but there is text/html which is all we need. We can't safely load that HTML into the DOM but I believe if we use [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) to parse/translate then that should work great.

**Comment by jcheng5** [comment]
I had ChatGPT take a stab at it, seems to work OK with Numbers and Google Sheets. I haven't tried it on Excel, but I'm sure it'd be a simple tweak. [shinylive link](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAS2NZlWLrKYGUydFhADmASQDyAHQj1GTVFDIALADYsARhy48mABSXKZMlp269FEACZQAzkzsKrx2Q2a3lw7NvNMAguh4TGIQqACuZLZBEhHhkUF8cLa2bBBBdHBQhGQsAG5w6ZRWcHSFAI5BYSwuaKgA+lVMALxMVVhQInB1NKpVVgAUMkzDrSwYZB22GLZk2Kpwg2AUAB4TGVBMIADunhQAtLaKhHCIChkA3Ew0pGR7NLAsqtinuVB0-Xt7GrZ3N3swpGIhyycAAlOcAL5SMCgvBDEZtYSEXrFOoAK1s-QMKn6dW6jy6dVB7Qy5CYAHomNDFDM4HtCLZchgMdDYfDhojQhE6isyHU3plFgzctCgqooBo4KomtCDLSmABhPgANSYNgmTGUJTgoqYDC2tiaAA4giRVIajQAGNkQEajDDEWLc9VQbp0WALaETDTzVlwiCglwyYo0Ji2Er5d7COKnEJxKJMR1kGNMGLJiIJ8PJVKnRLZ0igxDspgAASTcWLJdJxToGBdbo9xZDTG9836heLduFdRmdGaergZX60YiGGF7cDtrtIwyZDCdFtqCsGHWVjq44EQlEkn63d7oMnNXQ-YCqH6tQaLCC4bokcnYAheHA0Hg1Bp+2FzNs+CIN0oZGoclKQAMTCCBslSFt2EILVCAAa1YUMAAkABUAFkABkmBIcgoGEexSCeFsJV9WQwIg0hWFsVDMJQkiFmUMgYFUUFNnheYLDeG9+wgOAtiYAARCQ0IMOgb3bc52LgXgrGIQh+0UMSShJcNgLcTdhBEfpGOYoIvTgVZyR01RWUkqcOKYDRiCsbAFU8VQrFJftZMIDArJssd7McygzOGFhQ36dzbK80kMHmUQVGaJoWgARlYkBi38phAus4LHm8iBgEtABdDAIGsuAADkPSilpoRQvwACEMIAUVZNipztWd51tQQwjgXyRihRrEOSoK7PS0ksty-LimK+BSqpMAAHEJAkabar2PgkJqmqUL4PYaIwvYJAAJTEaaxEK+qEp64ZmoXFs6Hazrhm6u74Qu217nNDqZG6mQgKYUDwJySiyGg0hI14LbiJ9OAoMVFUZBoci-ta+iUOIJVlW0piWIa4YLMU7iWl4-ihJEriSgkqSZLkhTidrHG4DUxgNNENHdKm3kjPR0yybB+ZnLkjAynauhsESeZsm4RZWx1GFOos-V7BaPw6HdbAMDkGB+glldiANcFOeFftZeLDAYDQfp+n1VimgAPk7fxFagZXVbNrWxylc1J2nEYjZN3dXYt62zunY5VFUcYDLIBU-3IFc4FQcVjn6ckAD0pCkWwACoAB8U9sAASckRD0sBWWj2OQQT6F86CAByaFoSr92PaYBuPeZYhhEWOEYWLZumFb9va+MKXHuklrsMZMyPogHP+hcsJ4HIYlSEWd9JcL3kBSgXU7GwcDkrBZpLcxpg4CwDJ8nIAS4HuMJVDIUnzOk7D1FQKy3isASlA2FoT+4FgRGEKAqgarnzIGOZ+r86Dv0-kwDOGcmBbGELJLYYCWAv2IG-D+ExpaP2Mpgr+T9UEQKgRMDAnQyB4PFmHNmzEOYP14OvdY-YT5rDIWZeESUmaqDwUwAAZDwqiW06Lg04Xgg8R8saPz1i0CWSMUYiM-jrHqDDMgYFeL0CGLRhSdQhMfV64imAWV5NwzR4D0GQLwaQ6SFD9KGVLsIWhdoOFGIUfo4YyioCqMAe1fszisHFnukwbqEJFEPmykAA)

**Comment by mdaeron** [comment]
Outstanding. I can confirm it seems to work in Excel.

* If I understand correctly, in the short term I can copy what you just did and it should work (not a javascript person, but it seems simple enough).
* Is there a chance some future version of `ui.input_text_area()` will implement that functionality under the surface?
* Is there a chance some future version of Shiny will include a more polished (dare I say “shinier”?) tabular data input/editor?

Not sure what is the process for feature requests, but a tabular data editor would be at the top of my personal wishlist. Happy to help in any way I may be able to.

**Comment by GShotwell** [comment]
Editable data frames is near the top of our list. We spent a long time researching data grid implementations and ended up using [TanStack](https://tanstack.com/table/v8) in part because it made this implementation possible. I think we will probably reserve this functionality for editable data frames and not include it in the `ui.input_text_area` because it's a better fit.

It seems like we didn't have an issue for this, so I went ahead and [created one](https://github.com/rstudio/py-shiny/issues/659).

**Comment by mdaeron** [comment]
> Editable data frames is near the top of our list. We spent a long time researching data grid implementations and ended up using [TanStack](https://tanstack.com/table/v8) in part because it made this implementation possible.

Awesome! Thanks for the quick responses.

> I think we will probably reserve this functionality for editable data frames and not include it in the `ui.input_text_area` because it's a better fit.

That makes sense of course. The `ui.input_text_area` hack is only a stopgap.
