### ISSUE TITLE
How to run Shiny on a remote server

### ISSUE THREAD

**Issue by hai178912522** [rstudio/py-shiny#658]
In the remote server, I am unable to access 127.0.0.1:8000. How can I modify it to allow me to access this webpage?
shiny run --reload
INFO:     Will watch for changes in these directories: ['/Personal/zzz']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [32724] using StatReload
INFO:     Started server process [32735]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [32735]

**Comment by GShotwell** [comment]
The easiest way to run Shiny on a remote server is to [deploy it to Shinyapps.io](https://shiny.rstudio.com/py/docs/deploy-cloud.html#shinyapps.io) which is our free cloud hosting service. You can also deploy it to your own server using the open source [Shiny Server](https://shiny.rstudio.com/py/docs/deploy-on-prem.html#deploy-to-shiny-server-open-source) or our [commercial products](https://shiny.rstudio.com/py/docs/deploy-on-prem.html). 

We also have deployment options to [Hugging Face](https://shiny.rstudio.com/py/docs/deploy-cloud.html#hugging-face) or on a static site using [ShinyLive](https://shiny.rstudio.com/py/docs/shinylive.html).

**Comment by wch** [comment]
By default, shiny only listens on localhost, so it will not respond to remote network requests. If you want it to listen on all network interfaces, you can tell it to listen on `0.0.0.0`.

```
shiny run --host 0.0.0.0
```

Please keep in mind, though, that the hosting platforms mentioned by @GShotwell provide important features, like being able to run multiple apps on different http paths, starting applications only when the URL is visited, scaling to multiple processes when necessary, and graceful handling of crashed applications.
