### ISSUE TITLE
0.5.0: sidebar layout broken, along with some other missing bslib styling

### ISSUE THREAD

**Issue by lehiester** [rstudio/py-shiny#666]
Some of the bslib styling previously embedded into `bootstrap.min.css` was relocated between releases 0.4.0 and 0.5.0, but it isn't loaded into the web page.

Example - in 0.4.0 `.bslib-sidebar-layout` has styling applied to it in `bootstrap.min.js`, but as of 0.5.0, in the repo this styling was removed and relocated to `/shiny/www/shared/_x/bslib/components/sidebar/sidebar.css`, and this file is not currently being loaded in the page.  This produces a visibly different layout in the following minimal example when switching between `pip install shiny==0.4.0` and `pip install shiny==0.5.0`:
```
from shiny import App, ui

app_ui = ui.page_fluid(
    ui.layout_sidebar(
        ui.panel_sidebar('Sidebar content'),
        ui.panel_main('Main content')
    )
)

app = App(app_ui, None)
```

Not super familiar with the codebase, so I'm not sure where this is controlled or what the best resolution is.  Thanks!

**Comment by wch** [comment]
The fix is in Shiny 0.5.1, which is now on PyPI.
