### ISSUE TITLE
How to put panel_sidebar on the side?

### ISSUE THREAD

**Issue by basnijholt** [rstudio/py-shiny#671]
Thanks for this awesome package, in just 2 hours I had a [basic app](https://basnijholt.github.io/adaptive-lighting/) running (deployment included!)

I have been struggling to understand how to make the `panel_sidebar` actually appear on the side? My suspicion is that it is related to the autosizing of the plots (which take the entire width).

According to this image in the docs, it should appear next to `panel_main` automatically.

<img width="281" alt="image" src="https://github.com/rstudio/py-shiny/assets/6897215/0de2211f-bb96-4e42-b89e-523000fcb1c9">

_from https://shiny.posit.co/py/docs/ui-page-layouts.html#common-structure_

Refs:
- my app: https://basnijholt.github.io/adaptive-lighting/
- source: https://github.com/basnijholt/adaptive-lighting/blob/main/webapp/app.py

**Comment by wch** [comment]
Hi, in Shiny 0.5.0, we had a bug with the sidebar (#666). We've just released an updated version with a fix, 0.5.1.

If you were using 0.5.0, please try updating to 0.5.1.

**Comment by jcheng5** [comment]
Nice application, @basnijholt!

**Comment by basnijholt** [comment]
Yes, it indeed works now! Thanks a lot 😄
