### ISSUE TITLE
Data frame selected rows intermittently returning None Type

### ISSUE THREAD

**Issue by GShotwell** [rstudio/py-shiny#676]
When selecting the fourth (not the 1-3rd) entry of the [data_frame example](https://shinylive.io/py/examples/#data-frame-grid) the row selection produces a `None` value which causes an error. Weirdly this seems to be specific to that particular entry and persists you reorder or filter the data.

**Comment by andrie** [comment]
I have a reprex of a similar (the same?) problem when pre-filtering the dataframe.

https://gist.github.com/andrie/33ae57d8156959d5482bb927cacdcc9a

**Comment by GShotwell** [comment]
The bug is caused by the index being dropped which seems to be what the data frame relies on for selection. A workaround is to call `df.reset_index()` after filtering. This is possibly related to #634.

**Comment by andrie** [comment]
I'm still getting the same error in my app, despite having installed the latest `pyshiny` codebase.

**Comment by andrie** [comment]
I've now managed to fix my app to work with the changes in the linked PR.

The important missing step was to call `dat.reset_index()` after filtering.

The modified app is at https://gist.github.com/andrie/595d9b439d7c29eac2c1c1bb963d8e7f
