### ISSUE TITLE
Multi-line text outputs

### ISSUE THREAD

**Issue by gramster** [rstudio/py-shiny#684]
I don't see a way to render multi-line text outputs? Is there? Else can this be a feature request?

**Comment by nealrichardson** [comment]
Just so I'm understanding: does [this app](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymigA8PUKVDswAHdBaRZlfCYIgHVQ8MiANygrOF0IlkY4ZVUQujCIgEo8e0dDYnc3D28yQLIfQuKIAtUWiFkaVjkEuRtXdwlyskqJFjgWFg5SAsQShwABQcrZpjmpNrkMauX2pjqa6eXHSTgyBToIXghKjFywm2a1R409UXQbDW0OEa65B7AAXwAukA) show what you're talking about, that you'd expect a newline (`<br/>`) in the output between "some" and "words"

**Comment by gramster** [comment]
Yes. I think the answer is to use output_ui - I was looking at options on output_text.
