### ISSUE TITLE
Please create a debug extension for VS-code

### ISSUE THREAD

**Issue by andrie** [rstudio/py-shiny#694]
Debugging shiny apps is hard, since it requires you to invoke the python debugger using `breakpoint()`.

Please create a VS-Code extension that implements the debugging API for shiny apps.

https://code.visualstudio.com/api/extension-guides/debugger-extension

**Comment by iainwallacebms** [comment]
Agreed, something to aid debugging would be really useful. The browser() function in R is such a time saver

**Comment by andrie** [comment]
@iainwallacebms, the equivalent to `browser()` in Python is `breakpoint()`.  You can use this in a very equivalent way.

Also, it seems the best way to currently debug shiny for Python is to configure a launch profile, as documented at https://shiny.posit.co/py/docs/install.html#vsc-debug

The debug part works really well, although it seems you have to separately point your browser to the running shiny app.  Unfortunately I haven't yet found a way to automatically start debugging the running app in simple browser.

**Comment by jcheng5** [comment]
I've added a new "Debug Shiny App" option next to the "Run Shiny App" option in the VSCode extension. It's merged to main but we haven't done a release just yet--hopefully in the next few days. Thanks for the suggestion!

https://github.com/rstudio/pyshiny-vscode/pull/17
