### ISSUE TITLE
Does Shiny Python support suspendWhenHidden?

### ISSUE THREAD

**Issue by jacksimpsoncartesian** [rstudio/py-shiny#707]
I'm using output_ui in a tab but it only renders (and the input values only work) when I click to view the tab. Is there any way to force it to render? I noticed R Shiny has a suspendWhenHidden argument that I can't get to work in Python.

**Comment by jcheng5** [comment]
You can replace the `@output` decorator with `@output(suspend_when_hidden=False)`.

(Hmmm, our [Outputs decorator documentation](https://shiny.posit.co/py/api/Outputs.html) is quite bare.)
